### ISSUE TITLE
Replace the Interface class with the standard ABC module and remove the 'I' prefix

### ISSUE THREAD

**Issue by thedrow** [datafolklabs/cement#192]
The zope interface concept is outdated and the [ABC module](http://docs.python.org/2/library/abc.html) is the standard way of creating abstract classes/interfaces.
It is supported from 2.6 onwards so there is no incompatibility with cement's supported python versions and it removes the responsibility of maintaining and documenting how the interface works.
Moreover, more people are familiar with the ABC module then with your own implementation so it decreases the learning curve greatly.
Should we start refactoring?

**Comment by derks** [comment]
This is now implemented in `portland` branch, which will be released as Cement 3 this year (finally).
