### ISSUE TITLE
Create Demo App To Highlight Key Features

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#286]
Many requests for a functional demo application that highlights the key features of building an application on the Cement Framework.

**Comment by toogy** [comment]
I'm still looking for that!

I just started looking at cement and I don't know what it's capable of :(

**Comment by derks** [comment]
This is now handled by the [Beginner Tutorial](https://docs.builtoncement.com/getting-started/beginner-tutorial/part-1-creating-your-first-project). Closing.
