### ISSUE TITLE
Global logging handler

### ISSUE THREAD

**Issue by dorneanu** [datafolklabs/cement#292]
Hi,

I'm struggling seting up the default logging handler for my application. Perhaps I'm missing sth but I couldn't find any information how to setup the log handler to be accessible from all classes.

I've built a simple application available at: https://github.com/dorneanu/cement-test

in `application_controller_base` I'm to able access the logging handler through `self.app.log`:

```shell
# python application.py   
[ERROR     ] Test error
[INFO      ] Test info
```

I'd rather have sth more general like importing the logging handler in my class. In `parser.py` for example I'd like to have sth like:

```python
from application_logging import log
...
log.info("bla bla")
```

Are there any best practices how to handle this? Of course I could pass the `app` object in `application_controller_second` to `Parser()` like this:

```python
parser = Parser(self.app, ...)
```
And in the `Parser` class I could access the logging handler again through `self.app`. I find that this approach is not that elegant. 

Any ideas how to solve this?

Cheers,
Victor

**Comment by dorneanu** [comment]
I kind of made this working (have a look at this [commit](https://github.com/dorneanu/cement-test/commit/e588fb8a4c0e579e13bfbc9f1900ba7ec4d7f817)). Is this the way it should work?

Thanks for commenting and pointing me into the right direction :)

**Comment by derks** [comment]
There are definitely different ways that you can do this.  Understandably, passing the `app` object around is not the most elegant solution, however that is the current mechanizm that all `handlers` used within the Framework.  In general, the `app` object is passed to `CementHandler._setup()` and therefore `self.app.whatever` is accessible.  

Alternatively, you can make your `app` object global within your `main` entry point.  For example:

**myapp.py**

```python
from cement.core.foundation import CementApp

class MyApp(CementApp):
    class Meta:
        label = 'myapp'

# define and setup the app outside of main()
app = MyApp()
app.setup()

# add a shortcut to the log object
log = app.log

def main():
    app.run()
    app.close()

if __name__ == '__main__':
    main()
```


And then from any other module:

```python
from myapp import log
log.info('This is test')
```

**Comment by dorneanu** [comment]
Ok.. I think I've got the basic idea. Thx!
