### ISSUE TITLE
"help" command

### ISSUE THREAD

**Issue by dploeger** [datafolklabs/cement#304]
Do you have an example for a "help" command? I have a multi-layered command structure and can easily use

script command --help

to display the help for that command. However, I'd like to also offer this way:

script help command

**Comment by derks** [comment]
@dploeger no example for that but there are plenty of different ways you could implement it.  The easiest, but probably the least elegant way would be to just shell out a command based on the parameters... for example:

```

from cement.core.foundation import CementApp
from cement.core.controller import CementBaseController, expose
from cement.core import handler
from cement.utils import shell

class Base(CementBaseController):
    class Meta:
        label = 'base'

class SubCommand(CementBaseController):
    class Meta:
        label = 'sub'
        stacked_on = 'base'
        stacked_type = 'nested'

    @expose(hide=True)
    def default(self):
        print('Inside SubCommand.default()')

class HelpCommand(CementBaseController):
    class Meta:
        label = 'help'
        stacked_on = 'base'
        stacked_type = 'nested'
        arguments = [
            (['command'], dict(help='command to display help for')),
        ]

    @expose(hide=True)
    def default(self):
        cmd = 'python myapp3.py %s --help' % self.app.pargs.command
        shell.exec_cmd2(cmd, shell=True)

class MyApp(CementApp):
    class Meta:
        label = 'myapp'

app = MyApp()
handler.register(Base)
handler.register(SubCommand)
handler.register(HelpCommand)
app.setup()
app.run()
app.close()
```


Basically... it just wraps making a shell call back to itself with the command line args moved around.  So, the following are the same:

```
$ myapp sub --help

$ myapp help sub
```


Hope that help!  There are more elegant ways to do it I'm sure, but really depends on how the app is laid out and this is simply the easiest/fastest approach to it.
