### ISSUE TITLE
Usage when using nargs='+' options

### ISSUE THREAD

**Issue by flatzo** [datafolklabs/cement#305]
Usage when there is an option with nargs='+' doesn't help much as argparse requires you to have the argument passed before the option (otherwise it doesn't know when to stop)

Maybe a way of representing it in that case would be 
``` 
usage : myapp (sub-commands ..) [options ...] {arguments ...} [options [...] ...] 
positional arguments:
  one
  two

optional arguments:
  -a
  -b

optional arguments (multiple values):
  -c C [C ...]
```

Any thoughts ?

**Comment by derks** [comment]
@flatzo the usage text is intended to be generic... though you can override it on each controller.  For example:

```python

class MyController(CementBaseController):
    class Meta:
        label = 'my_controller'
        usage = 'myapp (sub-commands ..) [options ...] {arguments ...} [options [...] ...]'
```

**Comment by flatzo** [comment]
Thanks for the tip that solves part of my problem. 

By opening this issue I was actually thinking of something even more generic: Like if there is an optional argument that requires multiple values, append the [options [...] ...] to the usage string and put those options in a separated paragraph when enumerating.

Would it make sense to add this feature ?

**Comment by derks** [comment]
@flatzo I am actually working on refactoring the controller code, which removes the "cementisms" in the current implementation.  The new controller setup doesn't interfere with ArgParse as much and therefore the `usage` would be exactly how ArgParse would have it which I think is more in line with what you are talking about.

Because the existing controller code is likely to be deprecated, it would make more sense just to override the `usage` manually for the time being.

**Comment by flatzo** [comment]
Good to know! Looking forward to that new release!

**Comment by derks** [comment]
Current `master` branch includes `cement.ext.ext_argparse.ArgparseController` which will eventually replace `CementBaseController`.  It is much more inline with Argparse, and does less customization to how the parser is implemented.  In particular, it does not stand in the way of the autogenerated usage/help output like `CementBaseController` does... so you get what you would expect from using `argparse.ArgumentParser` directly.

See: http://cement.readthedocs.org/en/latest/api/ext/ext_argparse/
