### ISSUE TITLE
Loading controller functions in another Python app, outside the CLI

### ISSUE THREAD

**Issue by timworx** [datafolklabs/cement#306]
I'm utilizing EasyEngine for quick site creation on an nginx stack, it's built with Cement, which is great. The problem is that I'd like to run many of the commands from another python app (without using something glitchy like Pexpect).

[Here](https://github.com/rtCamp/easyengine/blob/master/ee/cli/plugins/site.py#L306) you can see EESiteCreateController on line 306, it's a great example of what I'd like to call from within a python script. 

Any thoughts on how I might go about this? Thank you!

**Comment by derks** [comment]
Can you clarify why it is not possible to make a shell call to `ee` to perform the actions you want? Looks like there is a `--no-prompt` options which would imply you can call it programmatically and pass in everything in needs without prompting.  Is that not the case?

The trouble is that Cement Controllers are intended to be used to build out the CLI interface.  Even if you import it in Python, it will still be looking for `sys.argv` options to determine how to operate.

Happy to help, just want to clarify the use case and needs.

Thanks!

**Comment by timworx** [comment]
Hey derks - missed the notification for your response. 
Good catch, I realized shortly after posting this that there was a `--no-prompt option`. I wound up needing to dig deeper as my implementation with pexpect was acting quite buggy.

I'm calling it via `subprocess.call` now, and it works perfectly fine this way. It still feels a bit unpythonic to call a python script via shell from a python script. Although The Zen of Python does say "Simple is better than complex.", and that is the simple way at this point.
