### ISSUE TITLE
Adding arguments and coressponding functionality to core commands of cement app by means of Cement Plugin

### ISSUE THREAD

**Issue by rjdp** [datafolklabs/cement#318]
@derks i wonder if there's a way to add arguments through a plugin to a cement apps commands (command which are part of the core app) and also the functionality pertaining to this the argument integrated to the app by the plugin

**Comment by derks** [comment]
Hi @rjdp, this is already a feature.  You simply create a plugin with a controller that is `embedded` on an application controller.  Something like:

**/path/to/myapp.conf**
```
[myapp]
plugin_config_dir = /path/to/myapp/config/plugins.d
plugin_dir = /path/to/myapp/plugins
```

**/path/to/myapp/config/plugins.d**

```
[myplugin]
enable_plugin = 1
```

**/path/to/myapp/plugins/myplugin.py**

```python

from cement.core.controller import CementBaseController, expose
from cement.core import handler

class MyPluginController(CementBaseController):
    class Meta:
        label = 'myplugin'
        stacked_on = 'base'
        stacked_type = 'embedded'
        arguments = [
            ( ['-f', '--foo'], dict(help='myplugin foo option', dest='foo') ),
        ]

    @expose(help='myplugin sub-command of base controller')
    def cmd1(self):
        print("Inside MyPluginController.cmd1()")

def load(app):
    handler.register(MyPluginController)
```

Note, the above is an untested example for reference... but would be accessible as:

```
$ myapp cmd1 --foo bar
```

The [Plugin documentation](http://builtoncement.com/2.6/dev/plugins.html) has a similar example as well.

**Comment by rjdp** [comment]
@derks  its my bad which caused the misinterpretation , i should have given an use case, i'll  do it now 
# consider my core app's code -
```
from cement.core.foundation import CementApp
from cement.core.controller import CementBaseController, expose
from cement.core import handler

class MyBaseController(CementBaseController):
    class Meta:
        label = 'base'
        description = "My Application does amazing things!"
        arguments = [
            ( ['-f', '--foo'],
              dict(action='store', help='the notorious foo option') ),
            ( ['-C'],
              dict(action='store_true', help='the big C option') ),
            ]

    @expose(hide=True)
    def default(self):
        self.app.log.info('Inside MyBaseController.default()')
        if self.app.pargs.foo:
            print("Recieved option: foo => %s" % self.app.pargs.foo)

    @expose(help="this command does relatively nothing useful")
    def command1(self):
        if self.app.pargs.foo:
            print(" foo  => %s received inside MyBaseController.command1()" % self.app.pargs.foo)
        self.app.log.info("Inside MyBaseController.command1()")

    @expose(aliases=['cmd2'], help="more of nothing")
    def command2(self):
        if self.app.pargs.foo:
            print(" foo  => %s received inside MyBaseController.command2()" % self.app.pargs.foo)
        self.app.log.info("Inside MyBaseController.command2()")


class MySecondController(CementBaseController):
    class Meta:
        label = 'second'
        stacked_on = 'base'

    @expose(help='this is some command', aliases=['some-cmd'])
    def second_cmd1(self):
        self.app.log.info("Inside MySecondController.second_cmd1")

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        base_controller = 'base'
        handlers = [MyBaseController, MySecondController]

with MyApp() as app:
    app.run()
```
i can use myapp like this -
`rajdeep@rajdeep-ThinkPad-Edge ~   ./app.py command1 --foo bar
 foo  => bar received inside MyBaseController.command1()
INFO: Inside MyBaseController.command1()`
`
now is there a way, by adding a plugin to the above app,  we can serve commands like  

`./app.py command1 --name rajdeep`

whose output will be
` name  => rajdeep  received`


so what i want to do is create a plugin which makes available ,additional arguments to existing subcommand/command in the core app and adding functionality to respond to those additional arguments

**Comment by derks** [comment]
OK, so as I understand it you want the plugin to add additional arguments to an existing sub-command of the core app.  I am working on something for the new `ArgparseController` that will eventually replace `CementBaseController`, and will make this easier.... but yes, this is possible with plugins and hooks.

**myplugin.py**

```python
from cement.core.controller import CementBaseController, expose
from cement.core import handler, hook

def process_arguments(app):
    # something something with `name` after arguments are parse
    if app.pargs.name:
        print("Got MyPlugin Name Option  > %s" % app.pargs.name")

class MyPluginController(CementBaseController):
    class Meta:
        label = 'myplugin'
        stacked_on = 'base'
        stacked_type = 'embedded'
        arguments = [
            ( ['--name'], dict(help='myplugin name option', dest='name') ),
        ]

def load(app):
    handler.register(MyPluginController)
    hook.register('post_argument_parsing', process_arguments)
```

Essentially, the stacked/embedded controller adds the `--name` option to the `base` namespace, which will then be accessible as `app.pargs.name` along with all other arguments.  That said, the core app needs to know what arguments a plugin is providing in order to call them within itself.

Using a `post_argument_parsing` hook allows the plugin to process it's arguments after they are parsed, before the app's controller commands are dispatched.

Please let me know if that helps!

**Comment by rjdp** [comment]
@derks 
thanku very much bt it doesnt work as expected

since the response to the added argument is served for all the sub-commands which are at same level as the level the plugincontroller is stacked on .. plus the response to the added argument irrespective of the applicable sub-commands are identical

according to my requirement
 
./app.py command1 --name rajdeep  
gives output = Got MyPlugin Name Option  > rajdeep

and the commands "./app.py cmd1 --name rajdeep " , "./app.py second-cmd1 --name rajdeep  "  may  behave differently on the --name argument

but using ur workaround all commands ("./app.py --name rajdeep", "./app.py command1 --name rajdeep" ,"./app.py cmd1 --name rajdeep " , "./app.py second-cmd1 --name rajdeep  " )
behaves in same way as far as the delta respective to --name argument is concerned

**Comment by derks** [comment]
I see what you're saying, for sure.  In that case, you could define your own hook specific for each command.  Here is a tested/working example:

**myapp.conf**

```
[myapp]
plugin_dir = /path/to/myapp/plugins

[myplugin]
enable_plugin = 1
```

**myapp.py**

```python

from cement.core.foundation import CementApp
from cement.core.controller import CementBaseController, expose
from cement.core import hook

class Base(CementBaseController):
    class Meta:
        label = 'base'

    @expose()
    def cmd1(self):
        print("Inside Base.cmd1()")

        # run the cmd1_hook (plugins)... passing in the app object
        for res in hook.run('cmd1_hook', self.app):
            # do something with res... 
            print("Hook Return Value > %s" % res)

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        handlers = [Base]
        define_hooks = ['cmd1_hook']

def main():
    with MyApp() as app:
        app.run()

if __name__ == '__main__':
    main()
```

**myplugin.py**

```python

from cement.core.controller import CementBaseController
from cement.core import handler, hook

def my_cmd1_hook(app):
    print('Inside my_cmd1_hook')
    
    if app.pargs.foo:
        print('Got Foo Option > %s' % app.pargs.foo)

    return app.pargs.foo

class MyPluginController(CementBaseController):
    class Meta:
        label = 'myplugin'
        arguments = [
            (['-f', '--foo'], dict(help="myplugin foo option", dest='foo')),
        ]

def load(app):
    handler.register(MyPluginController)
    hook.register('cmd1_hook', my_cmd1_hook)
```

Running it:

```
$ python myapp.py cmd1 --help
usage: myapp.py (sub-commands ...) [options ...] {arguments ...}

Base Controller

commands:

  cmd1

optional arguments:
  -h, --help         show this help message and exit
  --debug            toggle debug output
  --quiet            suppress all output
  -f FOO, --foo FOO  myplugin foo option


$ python myapp.py cmd1
Inside Base.cmd1()
Inside my_cmd1_hook
Hook Return Value > None


$ python myapp.py cmd1 --foo bar
Inside Base.cmd1()
Inside my_cmd1_hook
Got Foo Option > bar
Hook Return Value > bar
```

**Comment by rjdp** [comment]
@derks thanxx for your invaluable support , as far as i can think for now this is an appropriate fix for my issue , although i will be testing this exhaustively by tomorrow and will keep u posted on this .

**Comment by rjdp** [comment]
@derks i tested ur solution for my use-case ,and it worked as expected .
