### ISSUE TITLE
Support changing log format

### ISSUE THREAD

**Issue by dploeger** [datafolklabs/cement#329]
I'd like to include the current timestamp into my app's log messages. However, it seems there isn't a way to configure that or am I missing something?

**Comment by derks** [comment]
@dploeger it is possible to override the log format of the file log, console log, and debug.  I realize in looking for the doc that some extension module were missing the documentation for meta-data options.  I've corrected this in git/master which will be available in the next stable version of Cement.  You can see the available meta options for the `LoggingLogHandler` here:

 * http://cement.readthedocs.org/en/latest/api/ext/ext_logging/#cement.ext.ext_logging.LoggingLogHandler.Meta


An example:

**myapp.py**

```python
#!/usr/bin/env python

from cement.core.foundation import CementApp
from cement.ext.ext_logging import LoggingLogHandler

FORMAT = "%(asctime)s (%(levelname)s) %(namespace)s : %(message)s"

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        log_handler = LoggingLogHandler(console_format=FORMAT)

with MyApp() as app:
    app.run()
    app.log.info('This is an info message')
```


Outputs:

```
[myapp] $ python myapp.py
2015-09-25 13:05:50,269 (INFO) myapp : This is an info message
```


You can override `file_format`, `console_format`, and `debug_format` in this fashion (all meta-options are overridable this way).  The `format` is rendered by the `logging` module, so you'll need to review the `loggin` documentation to know what keywords are supported in the format string.  This might help:
 
 * https://docs.python.org/2/library/logging.html#logrecord-attributes

**Comment by fxstein** [comment]
@derks Thank you for sharing. I was recently looking for it as well.

**Comment by dploeger** [comment]
Yes. I see the missing bits in the docs now. Thanks, @derks.
