### ISSUE TITLE
Support non-ascii encoding for email subject and body

### ISSUE THREAD

**Issue by cocasema** [datafolklabs/cement#338]
Current implementation of SMTPMailHandler fails to send non-ascii messages.
This could be fixed using MIMEText.

**Comment by derks** [comment]
@cocasema thank you for the report.  Would it be possible to add a [MCVE](http://stackoverflow.com/help/mcve)?  If not, then atleast an example of the subject/body that you're trying to send.

Thanks!

**Comment by cocasema** [comment]
Sure. Here is a small cement app to repro the issue and modified SMTPMailHandler to handle it.
https://github.com/cocasema/mcve/tree/master/cement-338

Exception:
```
Traceback (most recent call last):
  File "./smtp_utf.py", line 17, in <module>
    app.send()
  File "./smtp_utf.py", line 13, in send
    self.mail.send(body='Текст', subject='Тема')
  File "/home/<user>/.virtualenvs/<venv>/lib/python3.4/site-packages/cement/ext/ext_smtp.py", line 233, in send
    msg)
  File "/usr/lib/python3.4/smtplib.py", line 764, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 63-66: ordinal not in range(128)
```

**Comment by derks** [comment]
@cocasema awesome! This is super helpful.  Will get it into 2.8.0 before I complete and push it out.

**Comment by derks** [comment]
This is now resolved in master, though it only fixes py3.  Seems that py2 doesn't even open the file if non-ascii characters exist.

**Comment by cocasema** [comment]
Thank you!
