### ISSUE TITLE
Registering same handler multiple times causes exception

### ISSUE THREAD

**Issue by akhilman** [datafolklabs/cement#353]
According documentation:

> Register a handler object to a handler.  If the same object is already
        registered then no exception is raised, however if a different object
        attempts to be registered to the same name a ``FrameworkError`` is
        raised.

But it fails. Example code:
```python
from cement.core.interface import Interface
from cement.core.handler import CementBaseHandler
from cement.core.foundation import CementApp


class MyInterface(Interface):

    class IMeta:

        label = 'myinterface'


class MyHandler(CementBaseHandler):

    class Meta:

        interface = MyInterface
        label = 'myhandler'


with CementApp('myapp') as app:

    app.handler.define(MyInterface)
    app.handler.register(MyHandler)
    app.handler.register(MyHandler)

```

To fix it `obj` should be replaced by `orig_obj` in https://github.com/datafolklabs/cement/blob/master/cement/core/handler.py#L195

I will make PR soon.

**Comment by akhilman** [comment]
This is my first contribution. If I can do better I would like to know how.

**Comment by derks** [comment]
Merged.  Thank you for the contribution.
