### ISSUE TITLE
CementTestCase do not delete temporary file and directory

### ISSUE THREAD

**Issue by akhilman** [datafolklabs/cement#363]
I would like to add `tearDown` to `CementTestCase` wich will delete `self.tmp_file` and `self.tmp_dir`.

Also we can use app label as mkdtemp/mkstemp's prefix

**Comment by derks** [comment]
Not sure why the pull-request broke... it look'd OK.  I'll work this into next release though.

**Comment by akhilman** [comment]
@derks in many unittests there is overloaded `setUp()` but inherited `tearDown()`, `tearDown()` tries to delete files which not created by overloaded `setUp()`.

To make this PR work we should ether overload both `setUp()` and `tearDown()`, or insert super().setUp() to all overloaded `setUp()`'s.

**Comment by akhilman** [comment]
And excuse me for garbage, I not very experienced in git and playing not well with it.
