### ISSUE TITLE
warn method is deprecated

### ISSUE THREAD

**Issue by akhilman** [datafolklabs/cement#365]
```
.../cement/ext/ext_logging.py:324: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  self.backend.warn(msg, **kwargs)
```

**Comment by akhilman** [comment]
Should we also rename `ILog.warn()` to `ILog.warning()`?

**Comment by derks** [comment]
Yes, per the the doc `logging.warn()` is deprecated in Python 3.5 (as you mentined in Gitter, Thanks!):

 * https://docs.python.org/3.5/library/logging.html#logging.Logger.warning

> Note There is an obsolete method warn which is functionally identical to warning. As warn is deprecated, please do not use it - use warning instead.

Therefore, at this point `warn()` should be fully deprecated and removed in `master`.

**Comment by derks** [comment]
Correction on that... the `ILog` interface defines that the implementation provide `warn()` and doesn't mention `warning()`.  The interface should be modified to mention `warning()` (to be inline with the `logger` module that it is models after)... but the `LoggingLogHandler.warn()` should not be fully removed,  will need to keep the deprecation note there and continue support through Cement 2.x.  It can/will be dropped in Cement 3.
