### ISSUE TITLE
Refactor Tests to Comply with Flake8

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#378]
Currently, `flake8` is only run against `cement/` ... which is fine, but would be clean to also start enforcing and checking on `tests/` (which is, to say the least... pretty sloppy in places).

**Comment by subhashb** [comment]
@derks,
Would you want this cleanup done even if all tests will be moved to PyTest as per #424?

**Comment by derks** [comment]
@subhashb thanks for working on this...  it doesn't hurt to do it now, especially since moving to PyTest would take a lot of work and will be a while.  I really apprecaite your time on this... I can help complete the outstanding issues with flake8.

**Comment by subhashb** [comment]
@derks Thanks, that would be awesome 👍 😄. Most of them may be false positives, like the warnings related to `unicode()` when I on Python 3.
