### ISSUE TITLE
Support for Alternative Config File Extensions

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#379]
Currently application and plugin configurations are expected to end in a `.conf` or they are ignored.  This doesn't make sense for an application using JSON or YAML configuration files.

**Comment by derks** [comment]
Added in `cement/master` (2.9)...  This is now configurable via the `CementApp.Meta.config_extension` option (default `.conf`).

**Comment by akhilman** [comment]
directory importing works well. Now I'll add cythonized plugin support.
