### ISSUE TITLE
Support for cythonized Plugins

### ISSUE THREAD

**Issue by akhilman** [datafolklabs/cement#380]
Adding support for cythonized plug-ins seems to be simple as add one more search path to:
```
        dll_suffix = do_magick()
        paths = [
            os.path.join(plugin_dir, "%s.py" % plugin_name),
            os.path.join(plugin_dir, plugin_name, "__init__.py"),
            os.path.join(plugin_dir, "%s.%s" % plugin_name, dll_suffix),
        ]
```
in ext_plugin.py

But I don't know how to determine right dll suffix. For linux it seems to be `.so`, but for Windows and MacOS things seems not so simple.

**Comment by derks** [comment]
@akhilman can you try out latest `master` and verify that this all works for you?  Thanks!

**Comment by akhilman** [comment]
Works well for me. Thank you!
