### ISSUE TITLE
Allow Jinja templates inheritance

### ISSUE THREAD

**Issue by zacbri** [datafolklabs/cement#381]
Template inheritance with Jinja requires its environment to have defined a loader.

For regular template rendering, we don't need it since Cement loads the templates content his own way. But internally Jinja can't rely on cement.core.output.TemplateOutputHandler._load_template()

The idea is to set the Jinja loader at _setup time, based on the app settings:
* FileSystemLoader if template_dirs is defined
* else, PackageLoader if template_module is defined

If none of them is defined, we don't set the loader, but in any case we expose Jinja Environment as self.app.output.env so that we can manipulate it in our application.

PR coming shortly...

**Comment by derks** [comment]
@zacbri can you try the latest `master`.  I merged in PR #383 with a few minor changes.  Let me know if that looks good and we can close this out.

**Comment by zacbri** [comment]
@derks it's all good.  
Much cleaner solution indeed. Thanks for following up on this.
