### ISSUE TITLE
Question: how to ignore arguments

### ISSUE THREAD

**Issue by zacbri** [datafolklabs/cement#384]
One of the nested controllers in our app actually calls an external program and we need to pass all its arguments to this program.

It works fine for positional arguments, which we handle with "extra_arguments".

But Cement still tries to parse other arguments (-c, -f, ...) and throws an error since they are not defined in the controller. If we define them, then Cement handles them but they are not passed to the external application.

We could manually handle and forward them, but there are quite a few and it doesn't look like the cleanest solution.

Is there any way to disable argument parsing for a specific controller, or consider all of them like extra positional arguments ?

Thanks

**Comment by derks** [comment]
You can put them in quotes as the value to a single argument, but that might not be the most user friendly.  Would it be possible to provide a [MVCE](http://stackoverflow.com/help/mcve) so I can get a better idea of your use case?

**Comment by zacbri** [comment]
Let's say the external command can be called with:

`external_command action positional_arg`

it also supports args like

`external_command action --foo positional_arg`

I've mapped one Cement handler to external_command and handle extra_arguments, so that I can run `myapp external_command action positional_arg`

But if I try to run `myapp external_command action --foo positional_arg` I get an error: unrecognized arguments: --foo positional_arg

What I'd like to do, basically, is to disable args parsing for this sub-handler, so that everything after the handler itself is considered as an extra positional argument and can be passed unchanged to the external command.

**Comment by derks** [comment]
@zacbri I've worked up an example of how I would do this.  I just did a basic wrapper around the `ls` command:


**myapp.py**

```python

from cement.core.foundation import CementApp
#from cement.ext.ext_argparse import ArgparseController, expose
from cement.core.controller import CementBaseController, expose
from cement.ext.ext_argparse import ArgparseArgumentHandler
from cement.utils import shell


class ModifiedArgparseArgumentHandler(ArgparseArgumentHandler):
    class Meta:
        label = 'modified_argparse'

    def __init__(self, *args, **kw):
        super(ModifiedArgparseArgumentHandler, self).__init__(*args, **kw)
        self._unknown = None

    def parse(self, arg_list):
        # use parse_known_args instead of parse_args
        args, unknown = self.parse_known_args(arg_list)

        # store privately for later use
        self._unknown = unknown
        
        # only return args for current compatibility
        return args


class MyController(CementBaseController):
    class Meta:
        label = 'base'

    @expose(hide=True)
    def default(self):
        print("Inside MyController.default()")

    @expose()
    def ls(self):
        print("Inside MyController.ls()")
        print("Known Arguments: %s" % self.app.pargs)
        print("Unknown Arguments: %s" % self.app.args._unknown)
        full_command = "ls %s" % ' '.join(self.app.args._unknown)
        shell.exec_cmd2(full_command, shell=True)


class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        argument_handler = 'modified_argparse'

        handlers = [
            ModifiedArgparseArgumentHandler,
            MyController,
        ]


with MyApp() as app:
    app.run()
```

It looks like:

```
$ python myapp.py ls
Inside MyController.ls()
Known Arguments: Namespace(debug=False, suppress_output=False)
Unknown Arguments: []
myapp.py

$ python myapp.py ls -l
Inside MyController.ls()
Known Arguments: Namespace(debug=False, suppress_output=False)
Unknown Arguments: ['-l']
total 8
-rw-r--r--  1 derks  staff  1560 Jul 11 17:22 myapp.py

$ python myapp.py ls -l -a
Inside MyController.ls()
Known Arguments: Namespace(debug=False, suppress_output=False)
Unknown Arguments: ['-l', '-a']
total 8
drwxr-xr-x  3 derks  staff   102 Jul 11 17:19 .
drwxr-xr-x  4 derks  staff   136 Jul 11 17:18 ..
-rw-r--r--  1 derks  staff  1560 Jul 11 17:22 myapp.py

$ python myapp.py ls -lah
Inside MyController.ls()
Known Arguments: Namespace(debug=False, suppress_output=False)
Unknown Arguments: ['-lah']
total 8
drwxr-xr-x  3 derks  staff   102B Jul 11 17:19 .
drwxr-xr-x  4 derks  staff   136B Jul 11 17:18 ..
-rw-r--r--  1 derks  staff   1.5K Jul 11 17:22 myapp.py
```


Note that some standalone arguments still might be caught by the argument parser.  In the above, passing `-lah` or `-l -a` all arguments are passed to `ls`.  However if I pass `-l -a -h`, the `-h` triggers the help output of `myapp.py`.  I think the `-h`, `--debug`, and `--quiet` are the only things that will interrupt what you're doing.

Does that work?

**Comment by zacbri** [comment]
Works like a charm!

Thanks for the detailed example, very much appreciated.

**Comment by derks** [comment]
@zacbri I've built this feature into `master` (See Issue #390). 

```python
from cement.core.foundation import CementApp
from cement.ext.ext_argparse import ArgparseArgumentHandler

class ModifiedArgparseArgumentHandler(ArgparseArgumentHandler):
    class Meta:
        label = 'modified_argparse'
        ignore_unknown_arguments = True


class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        argument_handler = 'modified_argparse'

        handlers = [
            ModifiedArgparseArgumentHandler,
        ]


with MyApp() as app:
    app.run()
```

**Comment by zacbri** [comment]
Awesome, works fine for me ;)
