### ISSUE TITLE
JsonOutputHandler Doesn't Pass Keyword Args to json.dumps()

### ISSUE THREAD

**Issue by dbrady-work** [datafolklabs/cement#385]
I'm trying to render some JSON that has some Decimal values and I get the error "Decimal('9.09') is not JSON serializable". I would like to be able to call something like self.app.render(x, cls=DecimalEncoder), where I can use the keyword arguments found in the JSON python library. Is this possible?

Thanks

**Comment by derks** [comment]
This is actually a bug in `JsonOutputHandler` ... the `render()` function takes `**kwargs` but doesn't do anything with them... but it should be passing them down to `json.dumps()` ... which should fix your issue.  Give me a few and I'll try and work it in quickly.

**Comment by akhilman** [comment]
This problem could be solved by pre_render hook which converts decimals to floats or strings.
I had same problem but with numpy.float64.

**Comment by derks** [comment]
Right, good call... that's exactly what the `pre_render` hook is intended for... altering the data before the output handler renders it.

**Comment by derks** [comment]
@dbrady-work can you try `cement/master` and see if the `self.app.render(x, cls=DecimalEncoder)` idea works for you?  The `**kwargs` are now being passed down to `json.dumps()`.

**Comment by dbrady-work** [comment]
@derks It works!!!! Thank you so much.
