### ISSUE TITLE
Use ujson as optional dependence

### ISSUE THREAD

**Issue by akhilman** [datafolklabs/cement#387]
`ujson` is fast json encoder/decoder with same interface as in `json`,
I propose to try import ujson first:
```
try:
    import ujson as json
except:
    import json
```

**Comment by akhilman** [comment]
Or perhaps I should just make new output `ujson` handler.

**Comment by derks** [comment]
Making a separate extension might be overkill.  Maybe we can just add `JsonOutputHandler.Meta.json_module == 'json'` ... and move the import to `_setup()` based on the module.  That way, it can all work the same but the developer can optionally use (and require) `ujson`. Maybe?

**Comment by akhilman** [comment]
Nice idea, We can use importlib/imp.

**Comment by derks** [comment]
I've got a branch going.. using config settings to override the module.  Like:

```
[output.json]
module = ujson
```

Same for `config.json` (`JsonConfigHandler`).

**Comment by derks** [comment]
@akhilman I've added an experimental feature to resolve this.... as all the other avenues I was taking had some random caveats that I wasn't liking.  I started to build out the alternative `ujson` extensions, but felt like it was all just too much just to change an imported module.  I had the thought of supporting an alternative module mapping for one off cases like this.  It doesn't have very wide usage, but significantly simplifies this use case where we just want to use ``ujson`` in place of ``json``.

You can try this:

```python
class MyApp(CementApp):
    class Meta:
        extensions = ['json']
        alternative_module_mapping = {
            'json' : 'ujson',
        }
```

The `json` and `json_configobj` extensions have been updated to support this.  Effectively, `json` will be used by default however if there is an *alternative module mapping* it will load the alternative and use that instead.

**Comment by akhilman** [comment]
This solution looks tricky for me, Why not to use simple handler configuration and import module directly from handler that requires alternatives?

**Comment by derks** [comment]
Yeah, I'm iffy on it...  Kind of just a thought on how to handle this use case without having to write more extensions.  I appreciate your feedback..  I'll look at more sane alternatives next week.

**Comment by akhilman** [comment]
Some background. 
My application will use output handler to output tables from database 10000+ rows. Only with this scale ujson gives real speedup.
I can not imagine any configuration file with thousands of rows.

**Comment by derks** [comment]
@akhilman I've gone with an alternative resolution for this.  Can you try `master`, with something like the following:

```python

from cement.core.foundation import CementApp
from cement.ext.ext_json import JsonOutputHandler

class MyJsonOutputHandler(JsonOutputHandler):
    class Meta:
        json_module = 'ujson'

def override_json(app):
    app.handler.register(MyJsonOutputHandler, force=True)

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        extensions = ['json']
        hooks = [
            ('post_setup', override_json),
        ]

with MyApp() as app:
    app.run()
    
    # test that we're getting the right json
    json_handler = app.handler.get('output', 'json')()
    json_handler._setup(app)
    print(json_handler._json.__file__)
```

**Comment by akhilman** [comment]
Simpler solution:
```python
from cement.core.foundation import CementApp
from cement.ext.ext_json import JsonOutputHandler


class MyJsonOutputHandler(JsonOutputHandler):

    class Meta:
        json_module = 'ujson'


class MyApp(CementApp):

    class Meta:

        label = 'myapp'

        handlers = [MyJsonOutputHandler]


with MyApp() as app:
    app.run()

    # test that we're getting the right json
    json_handler = app.handler.get('output', 'json')()
    json_handler._setup(app)
    print(json_handler._json.__file__)
```
```
`--> python json_output.py
/home/ildar/projects/slivoglot-1/venv/svgt1-dev/lib/python3.5/site-packages/ujson.cpython-35m-x86_64-linux-gnu.so
```
But in general I like this solution.

**Comment by derks** [comment]
@akhilman for your use case that might work ok, but it is actually incomplete.  The purpose of requiring the `json` extension, and then overriding just the `JsonOutputHandler` via a hook is because there are other things provided by the `json` extension that we need (it provides several hooks that properly handle outputting JSON to console, etc).  

Regardless, as long as it works for your needs to get `ujson` in the mix, it's good. ;)

**Comment by akhilman** [comment]
Yes. I forgot about extension initialization.
