### ISSUE TITLE
Registering pre_setup hook and "with"

### ISSUE THREAD

**Issue by qs** [datafolklabs/cement#403]
Hi!

My real goal is to setup complex logging logic and I want to do the necessary stuff in pre_setup hook.

But I found no way to register pre_setup hook using:
```
with MyApp() as app:
    app.hook.register('pre_setup', logging_setup)
    app.run()
```
Because `CementApp.__enter__` calls `setup`.
Is the only way to do it rewrite without `with`:
```
app = MyApp()
logging_setup(app)
app.setup()
```
Or I can do anything better?

**Comment by derks** [comment]
Right, using the `with` operator that way wouldn't work for `pre_setup` hook for the reason you stated.  You could either break it out as you did above:

```python
app = Myapp()
app.hook.register('pre_setup', logging_setup)
app.setup()
app.run()
app.close()
```

Or, you could use a `post_setup` hook instead.  Any reason you can't use `post_setup`?

**Comment by derks** [comment]
There is also another route... you can register the hooks via `CementApp.Meta.hooks`:

 * http://builtoncement.com/2.10/api/core/foundation.html?highlight=hooks#cement.core.foundation.CementApp.Meta.hooks

```python
class MyApp(CementApp):
    class Meta:
        hooks = [
            ('pre_setup', logging_setup),
        ]

with MyApp() as app:
    app.run()
```

**Comment by akhilman** [comment]
Also this way should work
```
app = MyApp()
app.hook.register('pre_setup', logging_setup)
with app:
    app.run()
```

**Comment by qs** [comment]
Thanks! Registering in meta is what I was looking for.
