### ISSUE TITLE
Controller action prints to stderr instead of stdout

### ISSUE THREAD

**Issue by qs** [datafolklabs/cement#409]
This example code:
http://cement.readthedocs.io/en/latest/examples/app_version/#adding-a-version-option-to-your-app
prints BANNER to stderr, but I expect it to print to stdout as --help does.

**Comment by derks** [comment]
@qs this is a Python/Argparse issue, and not related to Cement.  Looks to be fixed in Python 3.4+

 * https://bugs.python.org/issue18920
