### ISSUE TITLE
exit_code not working as expected

### ISSUE THREAD

**Issue by eads** [datafolklabs/cement#413]
I do this:

```
app.exit_code = 64
```

And exit code is 0.

I do this:

```
app.run()
app.close(64)
```

And exit code is 0.

**Comment by derks** [comment]
@eads thanks for the feedback.  Any suggestion on what to add to the doc, or where/what to modify?

**Comment by eads** [comment]
I think the note would be best in: https://github.com/datafolklabs/cement/blob/master/doc/source/dev/cleanup.rst

Tangentially, dozens of news organizations used Elex to display election results for the US elections a few weeks ago, which in turn is built on Cement. Thanks so much for a kickass framework.

**Comment by derks** [comment]
@eads You just blew my mind... I had no idea!  Very cool...

**Comment by derks** [comment]
@eads I've updated the doc there... and also added Elex to the list of Projects Built on Cement.
