### ISSUE TITLE
Add conf.d/*.conf to config handler

### ISSUE THREAD

**Issue by akhilman** [datafolklabs/cement#414]
I would like to add support for `conf.d/*.conf` files to default config handler.

I need it because I have plugins with multiple handlers and would like to use standard `interface.handler` config sections in plugin's config files. Current plugin handler takes only first section from `plugins.d/pluginname.conf`.

Also `conf.d` more generic and obvious solution for modular application.

I will need some help with English spelling to write good documentation.

**Comment by derks** [comment]
@akhilman this makes sense, and should/could replace the need to `plugin_config_dir`.

**Comment by derks** [comment]
@akhilman do you still want to implement this, or should I more forward on it? I can rewrite/correct any documentation as necessary, don't worry about that.

**Comment by akhilman** [comment]
@derks I'll take a look in few days.

**Comment by akhilman** [comment]
@derks take a look my branch. Is this solution ok?

**Comment by akhilman** [comment]
I have much simpler solution that doesn't require any cement modification:
```python
# in app class Meta
config_files = [
    *filter(os.path.isfile, glob(os.path.join('/', 'etc', 'myapp', 'conf.d', '*.conf'))),
    os.path.join('/', 'etc', 'myapp, 'myapp.conf'),
]
```

**Comment by derks** [comment]
@akhilman that could work, but should still be implemented in Cement... and needs to account for `CementApp.Meta.config_extension` (like you're doing in the commit to your branch)... rather than hard coding `.conf`.

On that thought though, do you think `conf.d` and `CementApp.Meta.config_dirs` should also  replace `plugin_config_dirs` eventually?

**Comment by akhilman** [comment]
@derks Yes. `plugin_config_dirs` looks not obvious for me and it loads only first section of config file.

**Comment by derks** [comment]
`App.Meta.plugin_config_dir` was deprecated in Cement 3.0.0, and now all configs are loaded from any files found in `App.Meta.config_dirs`, which solves this issue.
