### ISSUE TITLE
How could I mock cement app logger

### ISSUE THREAD

**Issue by atomicus** [datafolklabs/cement#417]
Hi

Just (maybe) simple question.

How should I properrly mock logger when running Unit Test for Cement app?

**Comment by derks** [comment]
@atomicus could you provide an example test case (whether it works or not) so that I can better understand what you're trying to test for?

**Comment by atomicus** [comment]
For my kids, I leave example, as I solved it:

```
from mock import patch

class ConfigTestCase(imsTestCase):

    @patch("logging.log")
    def test_config_set(self,mock_logging):
        argv = ['test']
        with self.make_app(argv=argv) as app:
            app.log = mock_logging

```

**Comment by derks** [comment]
@atomicus thank you for the followup, and example.
