### ISSUE TITLE
Daemonizing without --daemon

### ISSUE THREAD

**Issue by atomicus** [datafolklabs/cement#418]
I have a controller method:

```  
    @expose(hide=False, help="Runs program as daemon.")
    def start(self):
        self.app.log.info("Starting daemon service");
        self.app.daemonize()
       #do something
```

starting it as:
`myApp start`

Runs it as daemon, without detaching it to another process.

To do it, i need to run it as:
`myApp --daemon start`

How can I state programatically that start should always detach, so I don't need to add `--daemon` arg.

**Comment by derks** [comment]
@atomicus thank you for the issue request, and many apologies for the late reply... I must have missed the notification for this one over the holidays.

I've pushed a change that will make this possible... it's not the most eligant, but the `daemon` extension needs to be completely refactored any way so I didn't want to spend a lot of time on it.  Try overriding the parsed arguments like so:

```python
    @expose(hide=False, help="Runs program as daemon.")
    def start(self):
        self.app.log.info("Starting daemon service");
        self.app.pargs.daemon = True
        self.app.daemonize()
        # do something ...
```

Currently in the `master` branch, will work in `stable/2.12.0`.
