### ISSUE TITLE
Question: How to set logger for daemonized app.

### ISSUE THREAD

**Issue by atomicus** [datafolklabs/cement#419]
Sorry for such a number for questions from my side, a bit of new commer to cement and python.

When daemonizing app, how do I set it to work with log.logging. 

Deamon extensions sets logger file to /dev/null.
How can I pass it to extension that I want to use files set in defaults['log.logging']['file']

**Comment by derks** [comment]
@atomicus I'm not sure what you mean? Logging is independent of the daemon extension so it would work as usual.  Just add the following (or similar) to your applications configuration file:

```
[log.logging]
file = /path/to/you/app.log
```

**Comment by derks** [comment]
Closing out.  Please add a comment if you're still having issues and we can reopen it.  Thanks.
