### ISSUE TITLE
Cement logs to stderr

### ISSUE THREAD

**Issue by atomicus** [datafolklabs/cement#422]
Given example:

```
from cement.core import foundation
app = foundation.CementApp('myapp')

# First setup the application
app.setup()

# Run the application (even though it doesn't do much here)
app.run()

# Log a debug message
app.log.debug('This is a debug message.')

# Log an info message
app.log.info('This is an info message.')

# Log a warning message
app.log.warning('This is a warning message.')

# Log an error message
app.log.error('This is an error message.')

# Log an fatal error message
app.log.fatal('This is a fatal message.')

# Close the application
app.close()
```

Will log everything to stderr, and nothing to stdout.
Anyway to fix it?

**Comment by akhilman** [comment]
AFAIK this is by unix design. You have `stdout | stdin` to pass data
through pipes and stderr to show to user what's going on. Information
for user should not go to stdin of next application in pipe.

If you would like to render some data to screen or to pipe then logging
is not way to do that. Consider to use [output handler][1] or direct
rendering with `print` or `sys.stdout`.

If you would like to pass your logging output to pipe use shell's output
redirection: `command 2>&1 | nextcommand`

[1]: http://cement.readthedocs.io/en/latest/dev/output/

**Comment by derks** [comment]
@atomicus this is not a Cement-ism or issue, it is how `logging.StreamHandler` defaults if no `stream` is given to it.  See:

 * https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler

> Returns a new instance of the StreamHandler class. If stream is specified, the instance will use it for logging output; otherwise, sys.stderr will be used.
