### ISSUE TITLE
Incorrect Subclassing in Handler Documentation

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#423]
Need to reference use of `super()` and make sure example are using it... currently, the example here is broken.

 * http://builtoncement.com/2.10/dev/interfaces_and_handlers.html#registering-handlers-to-an-interface

Ref: http://stackoverflow.com/questions/41361353/object-has-no-attribute-meta-in-python-cement-app

**Comment by subhashb** [comment]
@derks Will an explanation on how `super()` is involved and updating the handler example suffice to address this issue? I can give it a go.

**Comment by derks** [comment]
@subhashb Yeah, just a quick reference to point out that `super()` is required for any class functions that are being sub-classed/overridden... and ensuring the examples are using it.
