### ISSUE TITLE
[Question] Why are my commands appearing as subcommands?

### ISSUE THREAD

**Issue by julenpardo** [datafolklabs/cement#433]
Hello,

I'm wondering why the commands I've defined, appear as subcommands, instead of "main" commands.

For example, I've defined something like the following:

```python
    @expose(
        help='some help',
        aliases=['alias'],
        arguments=[
            (['args'], dict(action='store', nargs='*')),
        ]
    )
    def some_command(self):
        pass
```

And, when I execute the application for showing the help, this is how appears:

```
usage: app [-h] [--debug] [--quiet] {some_command, alias} ...

An app

optional arguments:
  -h, --help            show this help message and exit
  --debug               toggle debug output
  --quiet               suppress all output

sub-commands:
  {some_command, alias}
    some_command (alias) some help
```

The command invocation works fine; it's just that I was expecting to make the commands appear as in the [quickstart](http://builtoncement.com/2.10/dev/quickstart.html).

Many thanks for your work.

**Comment by akhilman** [comment]
Add this to your controller's Meta:
    stacked_on = 'base'
    stacked_type = 'embedded'

More info here: http://builtoncement.com/2.10/dev/controllers.html#addi
tional-controllers-and-namespaces

**Comment by julenpardo** [comment]
Hello @akhilman, many thanks for your quick response.

It doesn't work for me. Now I've realized that, perhaps is because I'm extending the class `ArgparseController`? I should have posted the whole code from the beginning.

The following is a simplified version of what I have:

```python
from cement.core.foundation import CementApp
from cement.ext.ext_argparse import ArgparseController, expose


class BaseController(ArgparseController):

    class Meta:
        label = 'base'
        description = 'My_app'
        stacked_on = 'base'
        stacked_type = 'embedded'

    @expose(hide=True)
    def default(self):
        self.app.args.parse_args(['--help'])

    @expose(
        help='Some command.',
        aliases=['c'],
        arguments=[(
            ['-f', '--foo'],
            dict(
                help='foo',
                action='store_true'
            ),
        ),
        ],
    )
    def command(self):
        self.app.log.error('here')


class MyApp(CementApp):

    class Meta:
        label = 'My_app'
        base_controller = 'base'
        handlers = [
            BaseController,
        ]

with MyApp() as app:
    app.run()
``` 

I'm using the `ArgparseController` instead of `CementBaseController`, because I want my commands to receive `arguments`. In this case just with `action='store_true`, but also storing the values, in combination with `nargs`, in other cases.

For the code above, for the following execution:

```shell
python example.py
```

The shown output is:

```
usage: My_app [-h] [--debug] [--quiet] {command,c,default} ...

My_app

optional arguments:
  -h, --help           show this help message and exit
  --debug              toggle debug output
  --quiet              suppress all output

sub-commands:
  {command,c,default}
    command (c)        Some command.
```

**Comment by akhilman** [comment]
Ok, now i see. Looks like a bug.

**Comment by derks** [comment]
@julenpardo I think I understand now.  You are asking why the output of '--help' is different than the QuickStart example?  All of the dicumentIon currently references use of 'CementBaseController' which will look different.  That said, You do want to use ArgparseController because it will be the standard moving forward.  

If you need to customize the output of how --help looks you might want to research how it would be done with Argeparse directly...  then I could help integrate that into Cement. CementBaseController is very hacky...  where ArgparseController uses proper ArgparseController mechanisms for creating subcommabds via subparsers.

**Comment by derks** [comment]
Apologies for messy comment, writing from my mobile...

**Comment by julenpardo** [comment]
@derks Yeah, that's what I want. The commands exposed for `ArgparseController` are, actually, the main commands of the app (at least in my specific case), so that's why I don't want to show them as sub-commands :)

I would be delighted to have a look to it and contribute to Cement, but I wouldn't be able to make an estimation since I would have to dive into it for the first time, and I'm quite busy with work actually :)

**Comment by derks** [comment]
@julenpardo I'm not exactly sure what you mean by `main commands` vs. `sub-commands`?  The usage between `CementBaseController` and `ArgparseController` is nearly the same, but the difference being that ArgparseController commands can have their own arguments, where CementBaseController only supports arguments on the controller.

```
$ myapp --base-controller-options [sub-command] --sub-command-options

$ myapp --base-controller-options [nested-controller] --nested-controller-options [sub-command] --sub-command-options
```

All commands are sub-commands whether it is CementBaseController or ArgparseController... the difference is how/where arguments/options are handled.

**Comment by julenpardo** [comment]
@derks I wanted to mean that, using the `ArgparseController`, the commands are shown, for `--help`, as `sub-commands`.

For example, for the quickstart example, the output is the following:

```
usage: myapp.py (sub-commands ...) [options ...] {arguments ...}

My Application does amazing things!

commands:

  command1
    this command does relatively nothing useful

  command2 (aliases: cmd2)
    more of nothing

  second-cmd1 (aliases: some-cmd)
    this is some command

optional arguments:
  -h, --help         show this help message and exit
  --debug            toggle debug output
  --quiet            suppress all output
  -f FOO, --foo FOO  the notorious foo option
  -C                 the big C option
```

But, using the `ArgparseController`, the `commands`, would be shown as `sub-commands`:

```
usage: myapp.py (sub-commands ...) [options ...] {arguments ...}

My Application does amazing things!


optional arguments:
  -h, --help         show this help message and exit
  --debug            toggle debug output
  --quiet            suppress all output
  -f FOO, --foo FOO  the notorious foo option
  -C                 the big C option

sub-commands:

  {command1, command2, cmd2, second-cmd1, some-cmd}
    command1                    this command does relatively nothing useful
    command2 (cmd2)             more of nothing
    second-cmd1 (some-cmd)      this is some command
```

**Comment by derks** [comment]
That's all arbitrary terminology really. They are the same... function the same, and are executed the same way.

—  
BJ Dierkes
Data Folk Labs, LLC
[e] derks@datafolklabs.com(mailto:derks@datafolklabs.com)
[w] datafolklabs.com(http://datafolklabs.com)

**Comment by julenpardo** [comment]
@derks Yeah I know, I was just wondering if it was possible to make the `ArgparseController` output like in the example of the quickstart. It's just an esthetic matter. :)

**Comment by derks** [comment]
Not something I'd have much insight into, and don't know that it is really worth your time.  The old output of `CementBaseController` was a complete hack and wouldn't recommend anyone go down that route as it can interfere with how ArgParse handled the output of things like nested commands/controllers (i.e. subparsers).

**Comment by derks** [comment]
Closing out.
