### ISSUE TITLE
Allow Env Vars to Override Any Configuration Setting

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#437]
By default, any configuration setting should be overridable by environment variables.

 * `app.config.get('myapp', 'foo')` overrided by `MYAPP_FOO`
 * All UPPERCASE
 * Convert special characters to `_` (`config['myapp']['foo.bar']`  would be `MYAPP_FOO_BAR`
 * Prefix defined by `App.Meta.environment_prefix` (Default: `app.label.upper()`)

As of Python 3.2 this is a keyword argument `fallback` to the `get()` method, which should make implementation rather easy, since today, this should already work:

 * `app.config.get('myapp', 'foo', fallback='bar')`

**Comment by mschneider** [comment]
any updates on this feature? is anybody working on this1?

**Comment by derks** [comment]
@mschneider no update, but I am currently sprinting on `portland/2.99.1` (Cement 3)...  and this is on the milestone.

**Comment by derks** [comment]
Added in `portland`:

**myapp.py**:

```python
import os
from cement import App, init_defaults

defaults = init_defaults('myapp', 'other')
defaults['myapp']['foo1'] = 'bar1'
defaults['other']['foo2'] = 'bar2'

class MyApp(App):
    class Meta:
        label = 'myapp'
        config_defaults = defaults

with MyApp() as app:
    app.run()
    print('Foo1: %s' % app.config.get('myapp', 'foo1'))
    print('Other Foo2: %s' % app.config.get('other', 'foo2'))
```

Usage:

```
### using config settings

$ python myapp.py
Foo1: bar1
Other Foo2: bar2


### overriding app level configuration

$ MYAPP_FOO1=not-bar python myapp.py
Foo1: not-bar
Other Foo2: bar2


### overriding secondary namespace (always prefix with MYAPP_)

$ MYAPP_OTHER_FOO2=not-bar python myapp.py
Foo1: bar1
Other Foo2: not-bar
```
