### ISSUE TITLE
Add GitHub Issue / Pull Request Templates

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#446]
* https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by morrme** [comment]
Do you already have an idea of what you'd like in each template? 

Would you prefer the templates to be placed in a .github/ folder or into the root directory?

**Comment by derks** [comment]
@morrme sorry for the delay in response.  I swear I'm not getting Github notifications!

Preferred in the `.github/` subdir.  The `CONTRIBUTING.md` should be based off of what is currently in the Contributing Doc:

- http://builtoncement.com/2.10/dev/contributing.html


Needs to be converted to Markdown.  The `ISSUE_TEMPLATE.md` should include:

```
Cement Version:
Operating System Version:
Python Version:
```

And a request to include a [MVCE](https://stackoverflow.com/help/mcve) that reproduces the problem... stressing the `minimal` aspect, the example should be an absolutely minimal, application agnostic example of reproducing the problem.

The `PULL_REQUEST_TEMPLATE.md` should reference testing... meaning something like, `Please ensure that all tests pass locally before submitting pull requests`.  Run tests via `make test`:

**Comment by samlikins** [comment]
I attempted to make the templates as simple as possible, so as not to confuse anyone, but included links to further their knowledge and gain specifics.
