### ISSUE TITLE
Add Doc/Link for New Developers to Contribute

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#447]
Starting to add the `low-hanging-fruit` label for things that new contributors can tackle quickly to get familiar with Cement, and contributing pull-requests, etc.  The `Contributing` doc should include a quick reference to this and link to:

 * https://github.com/datafolklabs/cement/labels/low-hanging-fruit

**Comment by samlikins** [comment]
I've made the addition to the contribution document, but once issue #446 is merged in, the contribution document in the ``.github`` directory needs to be updated to reflect the same changes.

> If you are new to Cement, looking for something quick to fix, or just want an
> opportunity to contribute to the project, review the ``low-hanging-fruit``
> `labels in the issue tracker <https://github.com/datafolklabs/cement/labels/low-hanging-fruit>`_.
