### ISSUE TITLE
Json Configuration File - log.logging file parameter

### ISSUE THREAD

**Issue by jagDanJu** [datafolklabs/cement#449]
Hey,

i want set the ‘file’ setting under the ‘[log.logging]’ config section via a configuration file.

How exactly can i do this? I have tried it with the following:

`{
    "log.logging": {
        "file": "logs/app.log"
    }
}`

Unfortunately this does not work.

Can anyone help me?

Thank You.

**Comment by derks** [comment]
@jagDanJu this worked fine for me (using `master/2.11.x` ... but should be same for `stable/2.10.x`)

**myapp.py**

```python
from cement.core.foundation import CementApp


class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        extensions = ['json']
        config_handler = 'json'
        config_extension = '.json'


with MyApp() as app:
    app.run()
    print('Log File: %s' % app.config.get('log.logging', 'file'))
    app.log.info('Log File Test')
```

**~/.myapp.json**

```json
{
    "log.logging" : {
        "file" : "./myapp.log"
    }
}
```

Usage:

```bash
$ python myapp.py
Log File: ./myapp.log
INFO: Log File Test

$ cat myapp.log
2017-04-26 16:27:10,700 (INFO) myapp : Log File Test

**Comment by jagDanJu** [comment]
@derks 

i have found the mistake.. 

I use the following parameter:

`log_handler = 'colorlog'`

If i replace the .json config with following code, then it works:

```
{
    "log.colorlog" : {
        "file" : "./myapp.log"
    }
}
```

Thanks boy.
