### ISSUE TITLE
Convert All Source Sphinx Documentation to Markdown

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#452]
Sphinx finally supports Markdown! 

- http://www.sphinx-doc.org/en/stable/markdown.html
- https://recommonmark.readthedocs.io/en/latest/

**Comment by samlikins** [comment]
I've converted the `.rst` files to `.md` by using a combination of `pandoc` and a huge amount of manual tweaking.  I'd like to verify the conversion by running Sphinx, what are the steps to generate the documentation?

**Comment by samlikins** [comment]
After reviewing the package and the documentation for Sphinx and Recommonmark, I was able to perform the documentation generation with errors.  One of the requirements files was missing `sphinx_rtd_theme`. 
 After adding that package and re-running the generation I received warnings:
```console
/vagrant/doc/source/api/core/arg.md:: WARNING: document isn't included in any toctree
/vagrant/doc/source/api/core/backend.md:: WARNING: document isn't included in any toctree
/vagrant/doc/source/api/core/cache.md:: WARNING: document isn't included in any toctree
...
/vagrant/doc/source/projects_built_on_cement.md:: WARNING: document isn't included in any toctree
/vagrant/doc/source/upgrading.md:: WARNING: document isn't included in any toctree
/vagrant/doc/source/whats_new.md:: WARNING: document isn't included in any toctree
```

Apparently `recommonmark` has issues interpreting `toctree` sections and according to the [recommonmark: AutoStructify Auto Toc Tree documentation](http://recommonmark.readthedocs.io/en/latest/auto_structify.html#auto-toc-tree) requires the sections to be listed out in buleted link format.  After attempting that I received an error:

```console
Exception occurred:
  File "/vagrant/.env/cement/local/lib/python2.7/site-packages/recommonmark/states.py", line 134, in run_role
    content=content)
TypeError: 'NoneType' object is not callable
```

Found out that Sphinx is [not documented that 1.6 breaks recommonmark](https://github.com/sphinx-doc/sphinx/issues/3800) and attempted regressing Sphinx to version `1.5.6`.  This resolved the error I was receiving, however it revealed an invalid character in a couple files:

```console
'ascii' codec can't encode character u'\u2019' in position 4: ordinal not in range(128)
```

I corrected those characters and found that the issue with the TOC was not in fact fixed.  With the following in the configuration:

```python
def setup(app):
    app.add_config_value('recommonmark_config', {
            'url_resolver': lambda url: github_doc_root + url,
            'auto_toc_tree_section': 'Documentation',
            'enable_auto_toc_tree': True,
            'enable_auto_doc_ref': True,
            'enable_eval_rst': True,
            }, True)
    app.add_transform(AutoStructify)
```

The TOC in the main `index.md` file was interpreted correctly, at least the first section directly following the **Documentation** heading, not the other two following or the other index files.  WARNINGs for all other files were still being generated.  I attempted to see if I could get `AutoStructify` to recognize the other TOCs by including the other headings in the configuration:

```python
def setup(app):
    app.add_config_value('recommonmark_config', {
            'url_resolver': lambda url: github_doc_root + url,
            'auto_toc_tree_section': [
                'Documentation',
                'Cement Core Modules',
                'Cement Utility Modules',
                'Cement Extension Modules',
            ],
            'enable_auto_toc_tree': True,
            'enable_auto_doc_ref': True,
            'enable_eval_rst': True,
            }, True)
    app.add_transform(AutoStructify)
```

This did not resolve anything further and in fact caused all the first TOC to not be converted.  Apparently the `auto_toc_tree_section` doesn't like lists.  After reviewing forums and articles further I found a couple more suggestions:
 * [Use m2r project](https://github.com/sphinx-doc/sphinx/issues/3800#issuecomment-355951388)
 * [Use rst for index files](https://purduecam2project.github.io/CAM2WebUI/basicSetup/sphinx.html#index-rst-setup)

Based on the level of complexity, I'm going to attempt the latter first and see if that is acceptable.

**Comment by samlikins** [comment]
I reinstated the `index.rst` files to provide the correct TOCs, reinstalled Sphinx version 1.6.6, and re-ran the documentation generation:
```console
Running Sphinx v1.6.6
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/3.4/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 85 source files that are out of date
updating environment: 85 added, 0 changed, 0 removed
reading sources... [100%] whats_new                                                                                                                   
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] whats_new                                                                                                                    
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
```

Everything seemed to run smoothly, however I found that several issues remain:
* `py-modindex.html` was not generated
* Generated index was missing all classes and methods
* `:ref:`, `:class:`, & `:mod:` aren't being interpreted
* External links (ie: `:issue:` & `:pr:`) aren't being interpreted
* Unicode characters aren't being converted to HTML entities
* Numerous other small differentials...

`recommonmark` doesn't seem to be an appropriate solution to implement Markdown, I'll attempt to use [`m2r`](https://github.com/miyakogi/m2r) and see if it fairs any better.

**Comment by samlikins** [comment]
I attempted to utilize m2r for Markdown support, however the Sphinx markup was being ignored still.  Additional issues cropped up while running the documentation generation:

```console
Running Sphinx v1.6.6
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/3.4/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 85 source files that are out of date
updating environment: 85 added, 0 changed, 0 removed
reading sources... [100%] whats_new                                                                                                                   
/vagrant/doc/source/api/utils/test.md:14: WARNING: error while formatting arguments for cement.utils.test.raises: 'function' object has no attribute '__bases__'
/vagrant/doc/source/projects_built_on_cement.md:3: WARNING: Duplicate explicit target name: "github".
looking for now-outdated files... none found
pickling environment... done
checking consistency... /vagrant/doc/source/api/index.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/changes.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/contributors.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/dev/index.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/examples/index.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/faq.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/license.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/projects_built_on_cement.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/upgrading.md: WARNING: document isn't included in any toctree
/vagrant/doc/source/whats_new.md: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] whats_new                                                                                                                    
/vagrant/doc/source/api/ext/ext_genshi.md:68: WARNING: undefined label: dev_output_handling (if the link has no caption the label must precede a section header)
/vagrant/cement/ext/ext_plugin.py:docstring of cement.ext.ext_plugin:19: WARNING: undefined label: application_plugins (if the link has no caption the label must precede a section header)
/vagrant/doc/source/changes.md:20: WARNING: undefined label: upgrading (if the link has no caption the label must precede a section header)
/vagrant/doc/source/changes.md:20: WARNING: undefined label: whats_new (if the link has no caption the label must precede a section header)
/vagrant/doc/source/dev/controllers.md:146: WARNING: undefined label: multiple_stacked_controllers (if the link has no caption the label must precede a section header)
/vagrant/doc/source/whats_new.md:31: WARNING: undefined label: application_plugins (if the link has no caption the label must precede a section header)
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 18 warnings.
```

Looks like `m2r` is another bust.  Markdown may not be a true option at the moment.

**Comment by derks** [comment]
@samlikins I really appreciate your efforts here, and apologize for lack of feedback on it.  I've also attempted several hacks to get Markdown working with Sphinx and have recently decided it just isn't going to happen at this point.

That said, over the last few weeks I've been working on separating the Developer Documentation from the API Reference.  I'm nearly done with that for Cement 2 (existing), but will likely not launch those changes until Cement 3 is released, or atleast in beta.

What I've done is kept all of the automatically generated API docs in Sphinx, and moved everything else out to pure Markdown documentation that will be hosted separately on [builtoncement.com](http://builtoncement.com).  I don't like separating them, but they do have different purposes so it isn't a horrible route either.

If you are interested in seeing the current state of things (for Cement 3 anyway), you can check out the `portland` branch and run `make api-doc` ... which is just the Sphinx API Reference.  Then, on the [datafolklabs/buildoncement.com](https://github.com/datafolklabs/builtoncement.com) repo, checkout the `hexo-theme` branch...  and run `hexo serve`.  It is a fork off of [Vue.js's](http://vuejs.org) site.  At a later time we can take all of the same Markdown and work it into another platform/theme/frontend like Hugo or anything else, but it was built for Hexo which is why that was chosen.  

Would appreciate any feedback you might have on it.

**Comment by samlikins** [comment]
@derks I took a swing at the documentation in the `portland` branch.  Started out by fixing the Vagrant dev/testing environment, then fixed requirements, updated the Sphinx configuration, then started down the road of correcting `WARNING`s from the API generation.  Pushing up and creating a PR momentarily.

**Comment by derks** [comment]
Closing this... developer documentation will be external to api docs in a separate system once Cement 3 is released.
