### ISSUE TITLE
Creating default config file at installation time

### ISSUE THREAD

**Issue by fabito** [datafolklabs/cement#456]
Hi, 

What would be a good approach for creating a default configuration file i.e `~/.myapp/config.yaml` , at installation time ?

thanks

**Comment by derks** [comment]
That is outside the scope of Cement, and would land more in the Package Management realm (RPM,DPKG,APK,etc).  Unless anything has changed, Python packaging doesn't account for this well.  This might help:

- https://stackoverflow.com/questions/10456279/python-setuptools-how-to-include-a-config-file-for-distribution-into-prefix-e

Best practices in Cement is that you set the default configuration via `CementApp.Meta.config_defaults`, and document or include an example config file with your source code.  Getting that installed on the users system is outside of Cements control.

The above link references including a script/utility that would generate a config file... so something like this might work for you:

```
$ mapp generate-config /etc/myapp/myapp.conf
```

Where `generate-config` is a controller function/command built in with your app to atleast make it possible to generate one after installation.

**Comment by fabito** [comment]
Thanks @derks ! I'll go for the `generate-config` approach !!
