### ISSUE TITLE
Ability to Override Output Handler Via Keyword Args

### ISSUE THREAD

**Issue by athak** [datafolklabs/cement#471]
Hi,
I'm new to Cement so bare with me if this is obvious somehow, I haven't found it in the docs.

My app needs to output certain data, planning to use Jinja for that. But for certain cases, I want to use the Tabulate extension. The default output handler is defined at the application level and I read I can specify an alternative output on the command line via -o. I want to be able to do that at the controller level. Is it possible?

Thanks,
Atha

**Comment by derks** [comment]
Really apologize for the delayed response.  Can you elaborate a bit more on what you want/need? Maybe with some psuedo command line examples of the commands you'd run, and their associated output depending on passed options?

As is currently, like you said, you can override the output_handler with the built in `-o` for supported output handlers (`json`, `yaml`, etc).  If you are using the recommended `cement.ext.ext_argparse.ArgparseArgumentHandler`, that would look like:

```
$ myapp -o tabulate some-controller some-command
```

Or with older `CementController`:

```
$ myapp some-controller some-command -o tabulate
```

Either way, the only thing "tabulated" would be whatever is passed via `app.render()`... presumably, that is only in `some-controller` or `some-command`...  so even though it is an application wide setting, it is only relevant to that one controller/command at runtime.

Does that make sense?

**Comment by athak** [comment]
Hi @derks,
My apologies if it wasn't clear from my initial posting. What I want to do is precisely avoid having to call the app with `-o` to switch output handler. Some controller/command combinations have to output tabular data but I don't want users to have to remember which/where to do that.

I guess I can try and take a look at what `-o` does and try to emulate that.

**Comment by athak** [comment]
I solved it by setting `jinja2` as the default output handler and doing the following inside the controller/commands that I wanted to use `tabulate` as the output:
```
self.app.output = self.app._resolve_handler('output', 'tabulate')
```
Doesn't seem too hackish, but is there another/better way?

**Comment by derks** [comment]
Ok, I understand now.  You want to override the `output_handler` for the controller... and not have to pass `-o` options.  That makes complete sense.

Your solution works, and there isn't really a better way currently.  Feels like this should be a feature of Cement.  Maybe a keyword argument on `app.render()` that could override the default.  Something like: `app.render(data, handler='tabulate')`.

**Comment by athak** [comment]
That would probably be the most elegant solution!

**Comment by derks** [comment]
Added in `portland`:

```python
app.render(data, handler='some_other_handler')
```
