### ISSUE TITLE
ArgparseController version argument multi-line fails

### ISSUE THREAD

**Issue by samlikins** [datafolklabs/cement#475]
I've recently started using `Cement` and set up a project with `BOSS`.  When testing the version output with a multi-line string, the string was restructured; the new-line characters were stripped and the string was output with wrapping.  I took a look at the source code of `BOSS` which also uses `Cement`, as they use a multi-line version output and I noticed the dev branch is having the same issue as I.

Example from `BOSS` (**boss/cli/controllers/base.py**):
```
...
BANNER = """
  _______  _______ _______ _______
 |   _   \|   _   |   _   |   _   |
 |.  1   /|.  |   |   1___|   1___|
 |.  _   \|.  |   |____   |____   |
 |:  1    |:  1   |:  1   |:  1   |
 |::.. .  |::.. . |::.. . |::.. . |
 `-------'`-------`-------`-------'
 Copyright (c) 2015 Data Folk Labs, LLC
 Version %s
""" % VERSION
...
        arguments = [
...
            (['--version'], dict(action='version', version=BANNER)),
...
            ]
...
```

Output from **dev branch**:
```
$ boss --version
_______ _______ _______ _______ | _ \| _ | _ | _ | |. 1 /|. | | 1___| 1___| |.
_ \|. | |____ |____ | |: 1 |: 1 |: 1 |: 1 | |::.. . |::.. . |::.. . |::.. . |
`-------'`-------`-------`-------' Copyright (c) 2015 Data Folk Labs, LLC
Version 0.9.21.dev20160721184921
```

Output from **tag 0.9.20**:
```
$ boss --version
  _______  _______ _______ _______
 |   _   \|   _   |   _   |   _   |
 |.  1   /|.  |   |   1___|   1___|
 |.  _   \|.  |   |____   |____   |
 |:  1    |:  1   |:  1   |:  1   |
 |::.. .  |::.. . |::.. . |::.. . |
 `-------'`-------`-------`-------'
 Copyright (c) 2015 Data Folk Labs, LLC
 Version 0.9.20
```

This example was taken directly from the BOSS project.  I noticed that it worked correctly in version 0.9.20, but the dev was failing.  When I looked into it deeper I noticed that the major difference was that the `BossBaseController` was no longer extending `CementBaseController` and was now extending `ArgparseController`.  When I changed my project to use `CementBaseController` and tested the multi-line version output it worked as expected.  This seems like an issue with `Cement` and not with `Argparse`, but I may be wrong.

**Comment by samlikins** [comment]
I've reviewed the code for `CementBaseController` and `ArgparseController`, noticed the applicable differences, and created a PR with the necessary changes to correct the issue with multi-line version  output.

**Comment by derks** [comment]
@samlikins this is something that's been bugging me since using ArgparseController for all my own apps...  I haven't had the time to track it down, so really thankful for the time you've put into it!  Should be merging in soon.

**Comment by samlikins** [comment]
@derks when will version 3.0.0 Stable become available?

**Comment by derks** [comment]
@samlikins I am hoping to have Cement 2.99.1 (portland/dev) out within the next few weeks... then based on feedback/testing, trying to get Cement 3.0.0 out by March or so.

**Comment by samlikins** [comment]
@derks good to know!  Thanks for the update...  Is their anyway to use the milestones to provide a estimated timeline of expectation?

**Comment by derks** [comment]
@samlikins I haven't set dates on milestones in a long while now, simply because it is difficult for me to stick to timelines at the moment due to other responsibilities.  That said, I also haven't had anyone really pushing me for delivery either... so, consider it "noted".  Once I've locked in all of the major changes... I will start looking at a more consistent delivery plan.

**Comment by samlikins** [comment]
@derks, understood!  I was more just curious if it was possible to do, I've not used milestones on GitHub previously, and didn't see a link to a page for them.  I was having a difficult time finding any information on the milestones for the project, and only stumbled upon then by accident.
