### ISSUE TITLE
Feature Request: Path to project directory

### ISSUE THREAD

**Issue by samlikins** [datafolklabs/cement#485]
Having a mechanism to derive the path to the project directory would be nice to have as an internal call.  I was able to achieve this in my `projectname/cli/main.py` file by performing the following:
```python
app_path = os.path.realpath('%s/../../..' % __file__)
```
This gave me the directory path to the parent directory of the `projectname` directory.

**Comment by derks** [comment]
I think this would already be the recommended solution... being that Cement itself doesn't enforce how/where the `main()` is.. Cement wouldn't know how many levels up is the 'root' dir.  I don't really see an official way of doing this, so I'l going to close this out.  If anyone has any thoughts, please feel free to reopen/comment.
