### ISSUE TITLE
Thread aware logging

### ISSUE THREAD

**Issue by kaplun** [datafolklabs/cement#489]
# Cement Issue Reporting and Feature Requests

Please include any of the following in bug/issue reports where it is relevant:

**System Information**

- Cement Version: 2.10.2
- Python Version: 2.7.13
- Operating System and Version: CentOS 6

**Steps to Reproduce (Bugs Only)**

- Setup an app with:

```
META = init_defaults('log.logging')
META['log.logging']['file_format'] = '%(asctime)s [%(process)s:%(threadName)s] (%(levelname)s) %(namespace)s : %(message)s'
META['log.logging']['debug_format'] = '%(asctime)s [%(process)s:%(threadName)s] (%(levelname)s) %(namespace)s : %(message)s'
```
- Spawn a thread and from within it `self.log.info('foo')`
- I would expect:

```
2018-04-17 05:23:46,311 [30906:Thread1] (INFO) my-app : foo
```

What I obtain instead is always:

```
2018-04-17 05:23:46,311 [30906:MainThread] (INFO) my-app : foo
```

I am understanding this is due to the fact that from the thread `self.log` actually refers to the singleton `logging` object. Would there be a way to obtain a `logging` object per thread?

**Comment by derks** [comment]
It is the same against Cement 2.10.4 and Python 2.7:

**myapp-cement2.py**:

```
from cement.core.foundation import CementApp
from cement.utils.misc import init_defaults
from cement.utils.shell import spawn_thread

META = init_defaults('log.logging')
META['log.logging']['file_format'] = '%(asctime)s [%(process)s:%(threadName)s] (%(levelname)s) %(namespace)s : %(message)s'
META['log.logging']['debug_format'] = '%(asctime)s [%(process)s:%(threadName)s] (%(levelname)s) %(namespace)s : %(message)s'


def thread1(app):
    app.log.info('inside thread1')

def thread2(app):
    app.log.info('inside thread2')


class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        meta_defaults = META

with MyApp() as app:
    app.run()

    t = spawn_thread(thread1, args=(app,))
    t.join()

    t = spawn_thread(thread2, args=(app,))
    t.join()
```

Output:

```
$ python2.7 myapp-cement2.py --debug
[snipped]
2018-04-17 11:52:37,934 [82736:Thread-1] (INFO) myapp : inside thread1
2018-04-17 11:52:37,934 [82736:Thread-2] (INFO) myapp : inside thread2
```

**Comment by kaplun** [comment]
Hi @derks, in my case I was directly using `threading.Thread`. I haven't thought using `spawn_thread`. So with `spawn_thread` you are confirming that things work. I'll check within my real application to see if simply using `spawn_thread` solves the issue.

**Comment by kaplun** [comment]
Dear @derks, thanks a lot for the time you spent in demonstrating the correct functioning of the framework. It was indeed due to a bug on my side. (`.run()` Vs.  `.start()`)
