### ISSUE TITLE
Identify All Tests That Do Not Include Atleast 1 Assertion

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#494]
A lot of tests have been added over the years which were added only for coverage but not actually asserting anything valuable for testing.  Would be helpful to have someone identify those tests, and possibly add at least one assertion to them.

This is a low-priority, good first issue... Please note if you're interested in this issue that it is **only relevant to the `portland` branch (Cement 3)** currently (or master once portland is merged).

**Comment by garroadran** [comment]
Hey there, I'd be interested in giving this a crack, but I'm not entirely confident I can do a great job. The way I see it, I'd get to know the codebase for a bit, add an assertion or two here and there, then toss a PR your way so I can get some feedback before I get in deep with all the tests.

If that sounds alright then sign me up! But I'll understand if you'd rather leave this to someone who knows the system a bit better.

**Comment by derks** [comment]
@garroadran thanks for your interest!  Essentially, what I'd be looking for is adding atleast one assertion to any existing tests that don't have any.  Getting more familiar with Cement would be ideal, however there is a lot of example to reference throughout all of the `tests/` directory.

All tests are PyTest, and are simple assertions.  The trick will be figuring out what to assert on.

The best thing to do now would be exactly what you said... make a small change and pull-request, and slowly build up from there.  The last thing I want is a huge PR for everything all at once... and I certainly don't want you wasting time going too deep down the wrong paths.

Let me know whatever questions you have... maybe joining slack would help (recently moved from Gitter so it is pretty empty/quiet currently).

- https://join.slack.com/t/cementframework/shared_invite/enQtMzUzOTIzMDQwNjEwLThkY2FiYWU5ZmQ5ZmEzNGMzMTkyMDgzNTk2MWI0MGU1YWNmNTVmODgxYWNlZjJkZDBmODc0ZjM2MDg5ZmYyOTA

**Comment by garroadran** [comment]
Oh yikes, so sorry. I thought I'd replied to this already!
I was a bit busy over the past few days, but I'll start taking a look at it tonight!

**Comment by garroadran** [comment]
@derks 
The slack link doesn't appear to work. Any chance I can get an updated one?

**Comment by derks** [comment]
Apologies: https://join.slack.com/t/cementframework/shared_invite/enQtMzU0OTc5MDQ4NDA0LWMwMzZiOTczZjM4ZjFiZDE3MDk4MzA5ZmYxNmZjNTk4NzUwMzcyN2VlMDc5NzIxYjQ1NzlmNzgyNDFjMWJmMWY

**Comment by garroadran** [comment]
Ok, this is only a starter list, but these are the tests that don't have any explicit assertions or `with raises` assertions in them in the tests/cli, and tests/core directories.

I suspect that a few of these are basically tests of the "I assert that calling this method does not raise an exception" style, although it's hard to be sure about the intent behind the test without an actual assertion there.

- [ ] `cli/test_main.py` - `test_app`
- [ ] `core/test_extension.py` - `test_load_extensions`
- [ ] `core/test_extension.py` - `test_load_extensions_again`
- [ ] `core/test_foundation.py` - `test_add_handler_override_options`
- [ ] `core/test_foundation.py` - `test_handler_override`
- [ ] `core/test_foundation.py` - `test_loaded`
- [ ] `core/test_foundation.py` - `test_passed_handlers`
- [ ] `core/test_foundation.py` - `test_add_arg_shortcut`
- [ ] `core/test_foundation.py` - `test_add_arg_shortcut`
- [ ] `core/test_foundation.py` - `test_reset_output_handler`
- [ ] `core/test_foundation.py` - `test_no_handler`
- [ ] `core/test_foundation.py` - `test_alternative_module_mapping`
- [ ] `core/test_foundation.py` - `test_quiet`
- [ ] `core/test_foundation.py` - `test_pre_render_hook`
- [ ] `core/test_foundation.py` - `test_config_dirs`
- [ ] `core/test_foundation.py` - `test_quiet`
- [ ] `core/test_foundation.py` - `test_none_template_handler`

**Comment by garroadran** [comment]
- [ ] core/test_hook.py - test_register_hook_name_not_defined
- [ ] core/test_hook.py - test_framework_hooks
- [ ] core/test_output.py - ? Needs further checking
- [ ] ext/test_ext_alarm.py - test_alarm_no_timeout
- [ ] ext/test_ext_argparse.py - test_coverage
- [ ] ext/test_colorlog.py - test_colorlog
- [ ] ext/test_ext_daemon.py - test_switch
- [ ] ext/test_ext_daemon.py - test_daemon
- [ ] ext/test_ext_generate.py - test_prompt
- [ ] ext/test_ext_generate.py - test_invalid_case
- [ ] ext/test_ext_generate.py - test_no_default
- [ ] ext/test_ext_generate.py - test_generate_from_template_dir
- [ ] ext/test_ext_generate.py - test_generate_default_command

**Comment by derks** [comment]
@garroadran does that last PR close this out?

**Comment by derks** [comment]
Sorry, I saw your comment about the PR addressing `core` and that you'd be moving on to `ext`.   Thanks!

**Comment by garroadran** [comment]
Yeah, sorry, I was hoping to be a bit further ahead by now, but it's been a crazy month with work. Should be able to sink my teeth into it a bit more this coming weekend.

**Comment by garroadran** [comment]
This is the last batch. Should be done in a week, two at the most.

- [ ] ext/test_ext_argparse.py - test_coverage
- [ ] ext/test_ext_generate.py - test_generate_from_template_dir
- [ ] ext/test_ext_generate.py - test_generate_default_command
- [ ] ext/test_ext_yaml.py - test_handler_override_options_is_none
- [ ] utils/test_misc.py - test_minimal_logger

**Comment by derks** [comment]
Closing out! This was a huge help... Thank you @garroadran!
