### ISSUE TITLE
User config file is not updated upon config.set() or config.merge() calls

### ISSUE THREAD

**Issue by rehmanz** [datafolklabs/cement#503]
# Cement Issue Reporting and Feature Requests

My application initially creates a config file in `~/.fusion/config`. It's updated via `UserConfigFactory` object successfully but changes are never written to the config file. 

**System Information**

- Cement Version: 2.10.12
- Python Version: 3.6.5
- Operating System and Version: Mac OS High Sierra (Version 10.13.4)

**Steps to Reproduce (Bugs Only)**

- Create `~/.fusion/config` file
```
fusion]
debug=true

[log.logging]
file=~/.fusion/fusion.log
level=DEBUG
to_console=true
rotate=true
max_bytes=512000
max_files=4
colorize_file_log=false
colorize_console_log=true

[code.repository]
type=
url=
token=

[builder]
type=
url=
token=
```

- Run the following unit test to trigger the config changes:
```
    def test_update_builder(self):
        with FusionApp() as app:
            app.run()
            UserConfigFactory(app).update(builder={
                "type"  : "circle",
                "url"   : "https://www.circleci.com",
                "token" : "secret123"
            })
```

- The following `UserConfigFactory` class will update the `self.app.config` object but does not update the `~/.fusion/config` file.

```python
import os

from pathlib import Path
from jinja2 import Environment

USER_CONFIG_TEMPLATE_FILENAME = "user.config"
USER_CONFIG_FILENAME = "config"
USER_CONFIG_DIR = "~/.fusion"

class UserConfigFactory:
    def __init__(self, app):
        self.app = app

    def create(self):
        """
        Create initial user config file if one does not exist already
        
        :return: None
        """
        try:
            user_config_file = os.path.expanduser("%s/%s" %(USER_CONFIG_DIR, USER_CONFIG_FILENAME))
            if not Path(user_config_file).is_file():
                # Fetch user config template
                user_config_template = "%s/%s" %(os.path.dirname(os.path.realpath(__file__)),
                                                 USER_CONFIG_TEMPLATE_FILENAME)
                with open(user_config_template) as f:
                    user_config_data = f.read()

                # Create skeleton user config
                Path(os.path.expanduser(USER_CONFIG_DIR)).mkdir(exist_ok=True)
                with open(os.path.expanduser(user_config_file), "w") as f:
                    f.write(user_config_data)
        except Exception as e:
            self.app.log.error("User Config Exception - create: %s" %e)

    def update(self, code_repo={}, builder={}):
        """
        Update configuration

        :param builder:
        :param code_repo:
        :return:
        """
        try:
            if builder:
                self.__update_section(section="builder", value=builder)

            if code_repo:
                self.__update_section(section="code.repository", value=code_repo)
        except Exception as e:
            self.app.log.error("User Config Exception - update: %s" %e)

    def __update_section(self, section, value):
        if self.app.config.has_section(section):
            for key in value:
                self.app.config.set(section, key, value[key])
            self.app.config.merge( { "fusion" : { section : value } })
```
Fusion CLI [unit test](https://github.com/fusionci/fusion-cli/blob/master/fusion/tests/test_user_config.py) is a good reference point. Please let me know if you need more info. Thanks!

**Comment by derks** [comment]
The Config Interface in Cement does not define any aspect of writing the configuration back to disk.  Because the config handler reads in from multiple source files, it could get quite messy for the framework to try and do that back to the files it read from.

In the `portland` branch, the config interface now defines `get_dict()` which will return a dictionary of the entire configuration.  This could be used to write or export and entire config file.

Perhaps a `write()` function would make sense as a feature for Cement 3.  It would read `get_dict()`, then write/export it to file in the given format to a given path (not the source config path) of the config handler implementation (text, json, yaml, etc).  It would have to be a implemented on a per-handler basis as that is what would define the output format.

**Comment by rehmanz** [comment]
@derks I would definitely vote for the `write()` function. There are times, at least in my application, where I need to update the config. The single source of truth should be the configuration file and it makes sense to have Cement update it.

Would appreciate if you can point me to the feature request link, if there is one, so I can keep an eye. For now, I will implement my own `write()` function. Thanks!

**Comment by rehmanz** [comment]
By the how do I implement a yaml config handler instead of basic [config_parser](https://docs.python.org/3.6/library/configparser.html) style. I would like Cement to read the initial config that is in a yaml format to begin with.

**Comment by derks** [comment]
@rehmanz you can use the included `yaml` extension:

- http://builtoncement.com/2.10/api/ext/ext_yaml.html


```python
from cement.core.foundation import CementApp

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        extensions = ['yaml']
        config_handler = 'yaml'
```

There is also the `config_file_extension = '.yml'` option, renamed to `config_file_suffix` in portland/cement3.
