### ISSUE TITLE
Slack Channel Invite link no longer valid

### ISSUE THREAD

**Issue by patrick-motard** [datafolklabs/cement#504]
The slack channel invite link listed in the readme is no valid anymore.

**Comment by derks** [comment]
It needs to be updated to: https://join.slack.com/t/cementframework/shared_invite/enQtMzUzOTIzMDQwNjEwLThkY2FiYWU5ZmQ5ZmEzNGMzMTkyMDgzNTk2MWI0MGU1YWNmNTVmODgxYWNlZjJkZDBmODc0ZjM2MDg5ZmYyOTA

**Comment by lighth7015** [comment]
That link is also no longer valid. :p
