### ISSUE TITLE
Command name override

### ISSUE THREAD

**Issue by ss-remygreinhofer** [datafolklabs/cement#529]
# Cement Feature Requests

As a developer I would like to have the ability to override the default name of a command.

A use case is the creation of an `import` command. As `import` is a reserved keyword in python, it prevents me from creating a function like that `def import(self):`.

**System info**

```bash
$ cement --version
Cement Framework 3.0.0
Python 3.7.0
Platform Darwin-17.7.0-x86_64-i386-64bit
```

**Comment by derks** [comment]
This will be an easy addition, and becuase it does not break backward compat it should be able to get into the next point release.

For reference, this can be used to override `ex()` in Cement 3.0.0:

```python
from cement import ex as cement_ex

class ex(cement_ex):
    def __init__(self, hide=False, arguments=[], label=None, **parser_options):
        super(ex, self).__init__(hide, arguments, **parser_options)
        self.label = label

    def __call__(self, func):
        func = super(ex, self).__call__(func)
        if self.label is None:
            self.label = func.__name__
        func.__cement_meta__['label'] = self.label
        return func
```
