### ISSUE TITLE
cement 3.0.0 is being offered to Python 2.7 via pip

### ISSUE THREAD

**Issue by allenatdecisiv** [datafolklabs/cement#534]
cement                       2.10.12
Python 2.7.15
Microsoft Windows [Version 10.0.17134.228]

```
> pip list --outdated
Package Version Latest Type
------- ------- ------ -----
cement  2.10.12 3.0.0  sdist
```

**Comment by derks** [comment]
Would you have any suggestion around this? I am not familiar with any options in PyPi to limit what versions of Python a package is available to.

**Comment by FlyinTeller** [comment]
Maybe [this](https://packaging.python.org/guides/dropping-older-python-versions/) helps?

**Comment by derks** [comment]
@FlyinTeller thanks for the info on that.  Should be resolved in next deploy.
