### ISSUE TITLE
Contents of plugin_dirs is printed to console

### ISSUE THREAD

**Issue by Mefu** [datafolklabs/cement#538]
**System Information**

- Cement Version: 3.0.0
- Python Version: 3.7.0
- Operating System and Version: Platform Linux-4.18.8-arch1-1-ARCH-x86_64-with-arch

**Steps to Reproduce (Bugs Only)**

- Override `plugin_dirs` in `App.Meta`
- Run any command, and it will print directories set in `plugin_dirs`

**Example**

```python
from cement import App

class MyApp(App):
  class Meta:
    label = 'myapp'
    plugin_dirs = [ 'test1', 'test2' ]

def main():
  with MyApp() as app:
    app.run()

if __name__ == '__main__':
  main()
```

Run `python myapp.py` and you will see `test1` and `test2` in output.

I think this is because of a forgotten debug code. You can see `print` function [here](https://github.com/datafolklabs/cement/blob/master/cement/core/foundation.py#L1388). I apologize if this is already fixed somewhere. I could not quite understand the branch system of repo to check if it is fixed in development branch or something.

**Comment by derks** [comment]
@Mefu Thanks for catching that... was indeed buried debugging code.
