### ISSUE TITLE
Cement not compatible with pipenv

### ISSUE THREAD

**Issue by gatewaynode** [datafolklabs/cement#549]
# Cement Issue Reporting and Feature Requests

**System Information**

- Cement Version: 3.0.2
- Python Version: 3.7.1
- Operating System and Version: MacOS 10.14.2

**Steps to Reproduce (Bugs Only)**

- Step 1: `cement generate project`
- Step 2: `pipenv install`
- Step 3: `pipenv install setup.py`

It appears as though pipenv doesn't fully support setup.py files.  I'm not 100% behind this being fixed, pipenv is interesting but is also prescriptive about sub-shell paths in a way I don't agree with.  That said, it does come with some nice security features and built in multi-environment management.

**Comment by derks** [comment]
@gatewaynode this is interesting... never worked with pipenv yet.  Trying to dig into it to find the equivalent of setuptools `console_scripts` but haven't found it yet.  What I did find is this

- https://pipenv.readthedocs.io/en/latest/advanced/#custom-script-shortcuts

**Pipfile**:
```
[scripts]
myapp = "python -m myapp.main"
```

Then `pipenv shell` and `pipenv run myapp` works.  Does anyone have any insight into how we can make `myapp` (console script) work out of the box as it does with setuptools currently after running `python setup.py {develop,install}`?

**Comment by garroadran** [comment]
I don't have any insight into it at the moment, but I'm willing to look into it if you still need help with this issue.

**Comment by Theaxiom** [comment]
Works flawlessly with this command: `pipenv install -e .` -- you can close this issue.

**Comment by derks** [comment]
Documentation has been added based on this thread. Thank you all for the feedback/insights. Please open a new issue if there is anything else that might be helpful to include here:

- https://docs.builtoncement.com/additional-topics/pipenv
