### ISSUE TITLE
daemon option must be explicitly declared

### ISSUE THREAD

**Issue by xray1111** [datafolklabs/cement#550]
- Cement Version: 3.0.0
- Python Version: 3.6.7
- Operating System and Version: macos 10.13.6

Hi!
When I add app.daemonize() before app.run() in the main.py, the program will report error below if I don't pass the '--daemon' option explicitly:
```
  File "/Users/xray/homework/face/aiface/aiface/main.py", line 65, in main
    app.daemonize()
  File "/Users/xray/anaconda3/envs/py36/lib/python3.6/site-packages/cement/ext/ext_daemon.py", line 208, in daemonize
    hasattr(app, 'pargs') and app.pargs.daemon is True:
AttributeError: 'NoneType' object has no attribute 'daemon'
```
And if I pass the '--daemon' option, it will run as a daemon and everything is ok. Maybe it's because the source code below as some issue (in file ext_daemon.py, line 207)?
```
    if '--daemon' in app.argv or \
       hasattr(app, 'pargs') and app.pargs.daemon is True:
        CEMENT_DAEMON_ENV.daemonize()
```

**Comment by xray1111** [comment]
I found a solution to solve this, add a hook function and call app.daemonize() in the function. and the hook name is 'post_argument_parsing'

**Comment by derks** [comment]
That’s right...  you could also put it in a controller (if you wanted a like a ‘serve’ subcommand use case).  Primary detail is that daemon ext is loaded during setup so you can’t call it before app.run.  The post_argument_parsing hook is a recommended usage.

**Comment by xray1111** [comment]
Thanks @derks ! I'll close this issue
