### ISSUE TITLE
How should I access app object in custom classes?

### ISSUE THREAD

**Issue by alirezastack** [datafolklabs/cement#566]
I have used `Cement` framework for one of my services, the problem I'm facing is that I don't have access to `app` inside of classes and there is not a way to import it in my classes. The question is how should I access the Cement app inside of my classes?

```python
from cement.core.exc import CaughtSignal
from cezoo.core.cart import CartService
from cezoo.core.exc import CeZooServiceError
from cezoo.controllers.base import Base


class CeZooService(App):
    """CE ZOO primary application."""

    class Meta:
        label = 'cezoo'

        # configuration defaults
        # config_defaults = CONFIG

        # call sys.exit() on close
        close_on_exit = True

        # load additional framework extensions
        extensions = [
            'yaml',
            'colorlog',
            'redis',
        ]

        # configuration handler
        config_handler = 'yaml'

        cache_handler = 'redis'

        # configuration file suffix
        config_file_suffix = '.yml'

        # set the log handler
        log_handler = 'colorlog'

        # register handlers
        handlers = [
            Base
        ]

    def run(self):
        cs = CartServer(self._meta.label, target_database)
        cs.start()


class CartServer():
    def __init__(self, service_name, db):
        pass
    def start():
        # starts a long running process


def main():
    with CeZooService() as app:
        try:
            app.run()
        except AssertionError as e:
            print('AssertionError > %s' % e.args[0])
            app.exit_code = 1

            if app.debug is True:
                import traceback
                traceback.print_exc()

        except CeZooServiceError as e:
            print('CeZooServiceError > %s' % e.args[0])
            app.exit_code = 1

            if app.debug is True:
                import traceback
                traceback.print_exc()

        except CaughtSignal as e:
            # Default Cement signals are SIGINT and SIGTERM, exit 0 (non-error)
            print('\n%s' % e)
            app.exit_code = 0


if __name__ == '__main__':
    main()

```

How can I have access to `app` object inside of `CartServer` class?

**Comment by namedLambda** [comment]
You have to create it likeso:
```python

class CartServer:
    def __init__(self):
         self.app = CeZooService()
         self.app.setup()
```
Note that when your CartServer class is exiting, it needs to call `self.app.close()`.

**Comment by derks** [comment]
@alirezastack re-opening for discussion as I'm not sure the above response was completely in line with what you want. Assumming that `CeZooService()` is the primary application here, then it would probably make more sense to run the app external to `CartServer()`, and then pass `self` to it as `app`. 

My approach would be:

```python
class CartServer():
    def __init__(self, service_name, db, app):
        self.app = app

    def start():
        # starts a long running process

class CeZooService(App):
    def run(self):
        cs = CartServer(self, app._meta.label, target_database, app)
        cs.start()
```


Because `CeZooService(App)` is the entry point  application that is interacting with the user/cli, it makes sense (to me) to perform all the logic as you normally would with Cement... but then just pass `self` to other classes that need to access the global app object.

**Comment by alirezastack** [comment]
@derks I first went with your approach, but I thought @namedLambda answer is best practice. thank you anyway. I will go with passing `self` to `CartServer()`.

**Comment by coccoinomane** [comment]
I had a similar issue: I need the `db` object to define my [pewee](https://github.com/coleifer/peewee) models, however the `db` is stored in the `app` object, which is not accessible to my models.

Turns out that you can attach the `db` to your models *at runtime*, using a proxy `db` object. This allows to define the models AND attach the `db` inside a cement hook, where `app` is accessible.

More details here > https://stackoverflow.com/a/45043715/2972183

Cheers,
Cocco

**Comment by ravensorb** [comment]
Would this still work in cement3? Or is there another way to access the app object from custom objects?

**Comment by derks** [comment]
@ravensorb there are several ways to access the `app` object. 1. pass it to the `class.init()` when instantiating your class (then call as `self.app`), or 2. depending on runtime flow you might use a hook. For most hooks, the app object is passed to the hook when it is executed, giving you the control then to pass that or attach it elsewhere.

- https://docs.builtoncement.com/core-foundation/hooks


There is also another dev (@TomFreudenberg) who has built a bunch of extensions for their project you might find interesting:

- https://github.com/datafolklabs/cement/issues/665

One of the extensions was built to solve this (or similar issue):

- https://github.com/tokeo/tokeo/blob/master/tokeo/ext/appshare.py

**Comment by TomFreudenberg** [comment]
Hi Shawn @ravensorb 

you can use it like this:

```python
from tokeo.ext.appshare import app

def myfunc():
    app.log.info(f'There are {count} words at {url!r}.')
```

and just enable the extension by main.py:

```python
        # load additional framework extensions
        extensions = [
            ...
            'tokeo.ext.appshare',
            ...
        ]
```

Just give me a not if you need additional help.

**Comment by ravensorb** [comment]
This helps a lot -- thanks!
