### ISSUE TITLE
Why Redis cache time is ignored when expire_time is present in config

### ISSUE THREAD

**Issue by alirezastack** [datafolklabs/cement#568]
# Cement Issue Reporting and Feature Requests

Please include any of the following in bug reports where it is relevant:

**System Information**

- Cement Version: 3.0.2
- Python Version: 3.6.7

**Steps to Reproduce (Bugs Only)**

- Set Redis cache configuration as below:
```
cache.redis:
    expire_time: 60
    host: 127.0.0.1
    port: 6379
    db: 0
```

- Add Redis cache handler to app Meta class: `cache_handler = 'redis'`

- And finally add `redis` to extensions:
```
extensions = [
            'yaml',
            'colorlog',
            'redis',
        ]
```

- Now after app is instantiated set a cache with an expiration time:
`self.cache.set(key='my_key', value='my value', time=20)`

- Interestingly enough general expiration time is applied (60 seconds) while I have provided time for this specific key. 

**NOTE: when I comment the general configuration now the `time=20` is applied if I remove time from `self.cache.set`, infinite expiration time will be set for the Redis key.**

**Comment by derks** [comment]
@alirezastack I am not able to reproduce this:

**Example**

```
$ python3 myscript.py
foo -> bar
foo -> None
foo -> bar
foo -> bar
```

**myscript.py**

```python
from time import sleep
from cement import App, CaughtSignal, Controller, ex, get_version

CONFIG = {
    'cache.redis' : {
        'host' : 'redis',
        'expire_time' : 1,
    }
}

class Base(Controller):
    class Meta:
        label = 'base'

    def _default(self):
        """Default action if no sub-command is passed."""

        # test default 1 sec
        self.app.cache.set('foo', 'bar')
        print(f"foo -> {self.app.cache.get('foo')}")
        sleep(3)
        print(f"foo -> {self.app.cache.get('foo')}")

        # test override 5 sec
        self.app.cache.set('foo', 'bar', time=30)
        print(f"foo -> {self.app.cache.get('foo')}")
        sleep(5)
        print(f"foo -> {self.app.cache.get('foo')}")


class MyApp(App):

    class Meta:
        label = 'myscript'
        config_defaults = CONFIG
        extensions = ['redis']
        cache_handler = 'redis'
        handlers = [Base]
        close_on_exit = True


def main():
    with MyApp() as app:
        try:
            app.run()
        except CaughtSignal as e:
            # Default Cement signals are SIGINT and SIGTERM, exit 0 (non-error)
            print('\n%s' % e)
            app.exit_code = 0


if __name__ == '__main__':
    main()
```

**Comment by alirezastack** [comment]
The sample code worked and interestingly enough my code works as expected too. It seems a mis-configuration in my side. Thank you for the time.
