### ISSUE TITLE
AttributeError: module 'cement.core.controller' has no attribute 'CementBaseController'

### ISSUE THREAD

**Issue by mozgbrasil** [datafolklabs/cement#570]
# Cement Issue Reporting and Feature Requests

**System Information**

- Cement Version: 3.0.4
- Python Version: 3.6 
- Operating System and Version: Ubuntu 18.04

**Steps to Reproduce (Bugs Only)**

![Captura de tela de 2019-06-05 11-59-01](https://user-images.githubusercontent.com/17202780/58966817-5ce08c80-8789-11e9-8856-f7a05aaf9cf3.png)

    $ eb --version
    Traceback (most recent call last):
      File "/home/marcio/.local/bin/eb", line 7, in <module>
        from ebcli.core.ebcore import main
      File "/home/marcio/.local/lib/python3.6/site-packages/ebcli/core/ebcore.py", line 19, in <module>
        from ebcli.core import ebglobals, base, hooks
      File "/home/marcio/.local/lib/python3.6/site-packages/ebcli/core/base.py", line 24, in <module>
        class EbBaseController(controller.CementBaseController):
    AttributeError: module 'cement.core.controller' has no attribute 'CementBaseController'
    marcio@marcio-Inspiron-5548:~/dados/mozgbrasil/magento2$ pip --version
    pip 19.1.1 from /home/marcio/.local/lib/python3.6/site-packages/pip (python 3.6)
    marcio@marcio-Inspiron-5548:~/dados/mozgbrasil/magento2$ pip check
    launchpadlib 1.10.6 requires testresources, which is not installed.
    twisted 19.2.0 has requirement zope.interface>=4.4.2, but you have zope-interface 4.3.2.
    docker-compose 1.24.0 has requirement docker[ssh]<4.0,>=3.7.0, but you have docker 4.0.1.
    docker-compose 1.24.0 has requirement jsonschema<3,>=2.5.1, but you have jsonschema 3.0.1.
    docker-compose 1.24.0 has requirement PyYAML<4.3,>=3.10, but you have pyyaml 5.1.
    docker-compose 1.24.0 has requirement requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1, but you have requests 2.22.0.
    docker-compose 1.24.0 has requirement texttable<0.10,>=0.9.0, but you have texttable 1.6.1.
    awsebcli 3.15.2 has requirement cement==2.8.2, but you have cement 3.0.4.
    awsebcli 3.15.2 has requirement colorama<0.4.0,>=0.3.9, but you have colorama 0.4.1.
    awsebcli 3.15.2 has requirement docker-compose<1.24.0,>=1.23.2, but you have docker-compose 1.24.0.
    awsebcli 3.15.2 has requirement future<0.17.0,>=0.16.0, but you have future 0.17.1.
    awsebcli 3.15.2 has requirement PyYAML<=3.13,>=3.10, but you have pyyaml 5.1.
    awsebcli 3.15.2 has requirement requests<2.21,>=2.20.1, but you have requests 2.22.0.
    awsebcli 3.15.2 has requirement semantic-version==2.5.0, but you have semantic-version 2.6.0.
    awsebcli 3.15.2 has requirement six<1.12.0,>=1.11.0, but you have six 1.12.0.
    awsebcli 3.15.2 has requirement urllib3<1.25,>=1.24.1, but you have urllib3 1.25.3.
    awscli 1.16.168 has requirement colorama<=0.3.9,>=0.2.5, but you have colorama 0.4.1.
    awscli 1.16.168 has requirement PyYAML<=3.13,>=3.10, but you have pyyaml 5.1.
    awscli 1.16.168 has requirement rsa<=3.5.0,>=3.1.2, but you have rsa 4.0.

**Comment by derks** [comment]
This is not an bug.  Somehow Cement 3.0.4 got pulled in, but the awsebcli requires Cement 2.8.2:

```
awsebcli 3.15.2 has requirement cement==2.8.2, but you have cement 3.0.4
```


You need to remove cement and install `cement==2.8.2` in your Python environment.

**Comment by mozgbrasil** [comment]
Thanks Brother

    # FIX: Error due to dependency updates
    
    pip3 uninstall cement --yes --verbose
    pip3 uninstall awsebcli --yes --verbose
    pip3 install awsebcli --upgrade --user
