### ISSUE TITLE
controllers with same label?

### ISSUE THREAD

**Issue by hamr** [datafolklabs/cement#574]
Cement2 allowed us to build cli argument structures like the following
```
$ myapp cmd1 run tasks
$ myapp cmd2 run tasks
```
as documented here: 
 https://cement.readthedocs.io/en/2.10/examples/controllers_with_same_label/

Is there something analogous in cement3?

**System Information**
- Cement Version: 3.4.0
- Python Version: 3.7
- Operating System and Version: Fedora 30

**Comment by derks** [comment]
@hamr sorry for the late reply.  In Cement 3 this isn't possible in the same way becasue previously it required the use of "aliases" and "aliases_only" which doesn't work with ArgParse the same way anymore.

My suggestion would be that `cmd1` is a controller, `run` is a method, and `tasks` is a positional argument.  You could then pass `tasks` off to a common handler class to keep it dry (maybe).

In that way, you could have `SecondController.run()` and `ThirdController.run()` which would not conflict.

**Comment by joe-mc-krusty** [comment]
I got on the train after Cement 3 release, never used Cement 2 at all so I can't relate to @hamr issue. But @derks suggestion is actually the way I've been dealing with this matter on my projects so far.

**Comment by hamr** [comment]
Thanks @derks  and @joe-mc-krusty.  I'll try that out.
