### ISSUE TITLE
myapp.py fails with module 'cement.core.backend' has no attribute 'defaults'

### ISSUE THREAD

**Issue by chainhead** [datafolklabs/cement#579]
**System Information**

- Cement Version: whatever gets installed with `sudo pip3 install cement` as on May 22, 2020.
- Python Version: 3
- Operating System and Version: RHEL 7

**Steps to Reproduce (Bugs Only)**

- Copy paste `myapp.py` from [here](https://cement.readthedocs.io/en/stable-2.0.x/dev/quickstart/#getting-warmer)
- Run with `python3 myapp.py`
- Result

```bash
Traceback (most recent call last):
  File "myapp.py", line 4, in <module>
    defaults = backend.defaults('myapp')
AttributeError: module 'cement.core.backend' has no attribute 'defaults'
```

**Comment by derks** [comment]
The app/docs you're referencing is for Cement 2, and the latest is Cement 3.  Apps built on Cement 2 are not forward compatible, and will need to be updated to run on Cement 3.  You should be good to just `pip3 install "cement<3"` which will install the latest version of Cement 2.
