### ISSUE TITLE
Generated README contains incorrect installation instructions

### ISSUE THREAD

**Issue by latacora-tomekr** [datafolklabs/cement#588]
The generated `README.md` for a new project contains the following installation instructions:

```
## Installation

$ pip install -r requirements.txt
$ pip install setup.py
```

I don't beleive `pip install setup.py` is a valid command.

**System Information**

Cement Framework 3.0.4
Python 3.8.5
Platform macOS-10.15.6-x86_64-i386-64bit

**Steps to Reproduce (Bugs Only)**

- `cement generate project ./todo`
- Hit enter through the prompts to accept all the defaults
- Open `README.md`
- Note `pip install setup.py` in the Installation section

**Comment by derks** [comment]
I feel like my Github notifications for this repo are not coming through, I've just seen several since this one for the first time.  Good catch. Should be `python setup.py install`.  Will fix in next sprint, easy fix for anyone looking to contribute.
