### ISSUE TITLE
Overriding config options with environment variables doesn't work correctly with surrounding `_` characters

### ISSUE THREAD

**Issue by lhriley** [datafolklabs/cement#590]
Cement should resolve environment variables in order to override any config options set by default according to this issue https://github.com/datafolklabs/cement/issues/437 and the code here:

https://github.com/datafolklabs/cement/blob/2c2ae1e50932601f5d5581f2640120657aaa9c25/cement/core/config.py#L109-L129

https://github.com/datafolklabs/cement/blob/2c2ae1e50932601f5d5581f2640120657aaa9c25/cement/ext/ext_configparser.py#L144-L160

In my testing, this appears to not work for config options which are wrapped in underscores (`_`). For example `MYAPP_FOO___BAR__` where:

```yaml
MYAPP:
    FOO:
        __BAR__: False
```

It should be noted that I typically use this format for designating dictionary key names containing metadata about the dictionary. In this case, the key / value pair stores and retrieves correctly from `self.app.config` when using normal `dict.get()` lookups, etc. This  appears to be an issue with how the config parser interprets environment variables.

The most obvious workaround to this problem is to rename all of the config keys until they work as expected. However, solving the core issue itself would be preferable.

**System Information**

- Cement Version: `3.0.4`
- Python Version: `3.8.6`
- Operating System and Version: `Linux Mint 20 Ulyana` / `Debian GNU/Linux 10`

**Example**

```python
import os
from cement import App, init_defaults

defaults = init_defaults('vars')
defaults['vars']['__broken__'] = 'broken'
defaults['vars']['working'] = False

class MyApp(App):
    class Meta:
        label = 'myapp'
        config_defaults = defaults

with MyApp() as app:
    app.run()
    print('broken: %s' % app.config.get('vars', '__broken__'))
    print('working: %s' % app.config.get('vars', 'working'))
    print(app.config.get_dict())
```

No environment variables:
```shell
python ./myapp.py
broken: broken
working: False
{'myapp': {}, 'vars': {'__broken__': 'broken', 'working': False}, 'mail.dummy': {'to': [], 'from_addr': 'noreply@example.com', 'cc': [], 'bcc': [], 'subject': 'Default Subject Line', 'subject_prefix': ''}, 'log.logging': {'file': None, 'level': 'INFO', 'to_console': True, 'rotate': False, 'max_bytes': 512000, 'max_files': 4}, 'controller.base': {}}
```

With environment variables:
```shell
export MYAPP_VARS___BROKEN__=test
export MYAPP_VARS_WORKING=confirmed
python ./myapp.py
broken: broken
working: confirmed
{'myapp': {}, 'vars': {'__broken__': 'broken', 'working': 'confirmed'}, 'mail.dummy': {'to': [], 'from_addr': 'noreply@example.com', 'cc': [], 'bcc': [], 'subject': 'Default Subject Line', 'subject_prefix': ''}, 'log.logging': {'file': None, 'level': 'INFO', 'to_console': True, 'rotate': False, 'max_bytes': 512000, 'max_files': 4}, 'controller.base': {}}
```

**Comment by derks** [comment]
@lhriley perfect report, I appreciate all the detail and functional example. Will investigate in next sprint (planning soon).

**Comment by derks** [comment]
Fixed in `master`, will be deployed with `stable/3.0.6`.
