### ISSUE TITLE
main website invalid slack channel link

### ISSUE THREAD

**Issue by madeinoz67** [datafolklabs/cement#594]
Just a heads up on the main website <https://builtoncement.com/>

under resources | getting help

**Comment by derks** [comment]
Damn, did not realize they expire (or maybe that is new).  Please use this till I figure out a better approach:

- https://join.slack.com/t/cementframework/shared_invite/zt-4j2pcyqc-Z9aFrz8mQSFueq31tfNNwg

**Comment by derks** [comment]
Resolved.
