### ISSUE TITLE
Set output handler in controller

### ISSUE THREAD

**Issue by saleweaver** [datafolklabs/cement#595]
How can I set the output handler on controller level without having the user input some option?

In MyApp's META I have

```
        handler_override_options = dict(
            output=(['-o'], dict(help='output format')),
        ) 
```

and I can set the output to tabulate like this, but I would like a certain controller to always output as tabulate, but others use the default jinja2 output handler. 
Is there a config I don't find in the docs that allows specifying an output handler per controller/method?

**Comment by derks** [comment]
@saleweaver no, handlers are all application level and I've never had a use case to have a different output handler on just one controller.  I can make this work though, give me a minute.

**Comment by derks** [comment]
@saleweaver I remember now, you can pass a handler to `app.render()`:

```
app.render(data, headers=headers, handler='tabulate')
```

Here's a working example... I used `json` output handler as default just as a quick example:

```python
from cement import App, CaughtSignal, Controller, ex, get_version


class Base(Controller):
    class Meta:
        label = 'base'

    def _default(self):
        self.app.args.print_help()


    @ex()
    def cmd1(self):
        self.app.render({'foo': 'bar'})


class Second(Controller):
    class Meta:
        label = 'second'
        stacked_on = 'base'
        stacked_type = 'embedded'

    @ex()
    def cmd2(self):
        headers = ['NAME', 'AGE', 'ADDRESS']
        data = [
            ["Krystin Bartoletti", 47, "PSC 7591, Box 425, APO AP 68379"],
            ["Cris Hegan", 54, "322 Reubin Islands, Leylabury, NC 34388"],
            ["George Champlin", 25, "Unit 6559, Box 124, DPO AA 25518"],
            ]

        self.app.render(data, headers=headers, handler='tabulate')

class MyApp(App):

    class Meta:
        label = 'myscript'
        output_handler = 'json'
        extensions = ['json', 'tabulate']
        handlers = [
            Base,
            Second,
        ]


def main():
    with MyApp() as app:
        app.run()


if __name__ == '__main__':
    main()
```

Output:

```
myapp $ python3 myscript.py cmd1
{"foo": "bar"}

myapp $ python3 myscript.py cmd2

| NAME               |   AGE | ADDRESS                                 |
|--------------------+-------+-----------------------------------------|
| Krystin Bartoletti |    47 | PSC 7591, Box 425, APO AP 68379         |
| Cris Hegan         |    54 | 322 Reubin Islands, Leylabury, NC 34388 |
| George Champlin    |    25 | Unit 6559, Box 124, DPO AA 25518        |
```


Does that work for you?

**Comment by saleweaver** [comment]
@derks Oh wow, it was so easy. 👍 I didn't find this documented, but it works, yeah. I usually need to output from templates in the app I'm writing, but a few controllers output data from a database, using tabulate for those handlers makes it much more convenient. This is the first app I've written with cement; great tool!
