### ISSUE TITLE
Extend the project at runtime with additional commands

### ISSUE THREAD

**Issue by mjurkus** [datafolklabs/cement#596]
Hi,

I have a CLI tool for internal project management. But it became a bit unwieldy and I'm looking to replace it.

Looked at `Cement` for a bit, but I couldn't find a way to satisfy one of my requirements:
Each project that is managed by CLI can provide an additional module that defines additional commands it can execute.

For example:
CLI default commands could be `install`, `release`, `version`
`Project_A` has a module `extensions.py`:

```
Command = collections.namedtuple(
    "Command", ["name", "help", "func", "parser", "use_project_state"]
)

def run_locally(manager, args):
    # implementation for run_locally

def run_locally_parser(parser):
    parser.add_argument("--debug", action="store_true", help="run in debug mode")

CUSTOM_COMMANDS = [
    Command(
        name="run_locally",
        help="Run the project locally",
        func=run_locally,
        parser=run_locally_parser,
        use_project_state=True,
    ),
]
```

So when I run `cli --help` in that particular project I'd like to see and execute the `run_locally_parser` function.

Is there a way to achieve that without a need to expose `cement` to other projects?

**Comment by derks** [comment]
@mjurkus this is what plugins was intended for... having a base application, with the ability to extend the application with internal, or third party plugins. 

- https://docs.builtoncement.com/core-foundation/plugins

The plugin layout generated by `cement generate plugin` sets up a directory based plugin with controller/templates/etc... but a plugin can also be just a single file:

- https://docs.builtoncement.com/core-foundation/plugins#single-file-plugins-vs-plugin-directories


Generally, a plugin would extend the application by registering a controller, adding additional commands/options to the app.

Some questions:

1. Is there a reason plugins don't work for your use case?
2. What do you mean by "not exposing cement"? Do you mean that you don't want project developers to have to learn the framework and how to use it, or something else.

Looking forward to helping sort it out, I'm sure Cement can do what you need... just need to fully understand the usecase.

Thanks!

**Comment by mjurkus** [comment]
Yes, eventually I found it :)

Thanks for the great tool!

**Comment by TomFreudenberg** [comment]
Hi @mjurkus @derks 

I guess I am struggling with the same question about "good" layouting a new CLI app with cement

We are building an app with several Sub-Commands classes like

```
app processing start --options
app processing build --options

app plot images --options
app plot graphs --options

etc.
```

1. Question

Should we implement each command as a file like app/controllers/processing.py or should we create each command as a plugin like processing plugin and plot plugin?

We never will use processing or plotting outside this app

2. @derks may you give some useful ideas of a PLUGIN or a EXTENSION - can't get out of the documentation what your ideas about that.

3. In our app we have to create several classes to implement core functionality. Where to place those files and libraries? I guess they should live at app/core/mymodules? Right?

Thanks for guiding thru that nice framework and use it "the right way"

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Hi @derks 

me again :-) hopefully a relevant question:

1. When working with plugins, where to place the tests for that. I have tried to organize those under

```
./myapp/plugins/myplugin/tests
```

as well as a "local" core module like

```
./myapp/plugins/myplugin/core
```

Is this like you "expect"?


2. I tried to activate a test plugin via config.yml but can't get it work.

If I enter in main.py `Meta` plugins = [ 'myplugin' ] it worked but not via YAML config.

```yaml
myapp:
  plugin_dirs = '/abspath/myapp/plugins'

myplugin:
  enable_plugin: 1
```

does not worked.

Thanks for your help
Tom

**Comment by TomFreudenberg** [comment]
Sorry @derks  - one more

Let's say my plugin command need additional packages like `pandas`

Where to define the requirement of that.

Do you expect to append that to the "app global" requirements.txt or may I create a requirements.txt also inside each plugin project folder?

**Comment by TomFreudenberg** [comment]
I placed the question in one block as #602
