### ISSUE TITLE
Use `extras_require` for optional extensions

### ISSUE THREAD

**Issue by mwchase** [datafolklabs/cement#604]
Currently, the process to make sure an optional extension will work appears to be:

1. Look at extension's source
2. Find any listed requirements
3. Add requirements to project

This is a little time-consuming, and it's theoretically brittle because Cement cannot enforce version requirements, and if a requirement is added, that will break consumers that weren't keeping track.
setuptools has an `extras_require` argument that allows users to request optional requirements.
For example, if setup were called with `extras_require={"jinja2": ["jinja2"]}`, then cement could be installed with `pip install cement[jinja2]` (or in a requirements file, etc).

This obviously isn't very compelling from the standpoint of writing shorter requirements, but it allows for a few things: as above, setting version requirements for dealing with compatibility issues, *changing* requirements in various ways, and having all of the optional requirements noted in a single file.

**Comment by derks** [comment]
@mwchase thank you so much for the great suggestion.  Use of `extras_require` has been pushed to `main` and will be released in `stable/3.0.8`. Documentation will be updated to reflect after it is deployed and tested via pip/pypi.
