### ISSUE TITLE
Duplicate redis service?

### ISSUE THREAD

**Issue by aronbeal** [datafolklabs/cement#605]
Hi, just checking - is there a reason you've [declared](https://github.com/datafolklabs/cement/blob/fece8629c48bcd598fd61d8aa7457a5df4c4f831/docker-compose.yml#L49) the redis service twice in docker-compose.yaml?

**Comment by derks** [comment]
Not at all... looks like a typo :/

**Comment by derks** [comment]
Fixed, thanks.
