### ISSUE TITLE
How to process multiple nested subcommand using Cement?

### ISSUE THREAD

**Issue by Graeme22** [datafolklabs/cement#607]
Hello, I'd like to process  one or more comma-separated subcommands similar to the example below:
```
cmd sub1 required1 --opt1 val, sub2 --opt1 val, sub1 required1
```

Is this possible using Cement? For my application, it is crucial that all of the options can be passed in a single command; often, it can't be broken up.

Obviously this can be done with some preprocessing:
```python
argv = 'sub_a req --opt1 foo --opt2 bar, sub_b req --opt1 foo --opt2 bar'.split(',')
argv = [i.split() for i in argv]
```

However this is more at the `argparse` level than the Cement level, so I'm wondering if there's a better way.

**Comment by derks** [comment]
@Graeme22 I need some clarity, as I'm not sure I completely understand the use-case.  So, you want to be able to execute:

```
cmd sub1 required1 --opt1 val, sub2 --opt1 val, sub1 required1
```

Which would effectively be the same as:

```
cmd sub1 required1 --opt1 val

cmd sub2 --opt1 val

cmd sub1 required1
```

Meaning, I could run the three commands independently... or run them all in one operation? I might need to know the actual details of the operation to understand what you're trying to accomplish... or some redacted version of it.

**Comment by Graeme22** [comment]
I've actually moved over to click and everything is working fine, so you can close this if you want.

Let me go ahead and expound on this though for posterity:

The commands wouldn't be run sequentially, so the functionality would be completely different if you were to run them separately. The application is a trading application, where you need to be able to place orders to buy multiple separate derivatives in a single order. So:

```
cmd buy 4 product1, sell 3 product2
```

A version without a comma would work as well.

**Comment by derks** [comment]
@Graeme22 thank you for additional info, and sorry to see you go... though Click is a great choice for CLI as well.

If I were building something like this with Cement (as-is, today), I'd suggest putting the core functionality of `buy` and `sell` into it's own class... and separate logic from user interface. Then you could have a `buy`, `sell`, or `buy-and-sell` or maybe `multiple-transactions` commands:

```
### call MyClass.buy(...)

$ cmd buy 4 product1


### call MyClass.sell(...)

$ cmd sell 3 product2


### call MyClass.buy(...) and MyClass.sell(...)

$ cmd buy-and-sell --buy 4 product1 --sell 3 product2


### call many (splitting args on : and ,) ... i know this is ugly but could work

$ cmd multiple-transactions --buy 4:product1,17:product8,2:product5 --sell 3:product2,4:product7
```


That is just an example for clarity, it could be "sexier" than that... but you get the idea. I prefer to separate logic from user-interface so the meat of everything would be in your logic class that does everything.... and the cli controller code is strictly interfacing with user (commands, arguments, etc).

Just a different way to skin it... good luck with the project, and again thanks for the followup so I could understand it better.
