### ISSUE TITLE
Documentation Site Cert is Expired

### ISSUE THREAD

**Issue by JP-Dhabolt** [datafolklabs/cement#608]
Not a bug related to the codebase itself, but just an FYI that the SSL Cert hosted at https://builtoncement.com/ expired on Thursday, July 29, 2021.  The site is still accessible, but users must click through the insecure site warning in most browsers to access.

**Comment by derks** [comment]
@JP-Dhabolt thank you for the heads up. I'm working on migrating off of that server (it's lived a long life and seems no longer supportable by certbot to renew the cert). Will resolve this ASAP.

**Comment by TomFreudenberg** [comment]
Hi @derks, maybe you put that site into a GitHub pages page. Very easy and support with Certificates and your own domain. Just as a hint - and without any costs

**Comment by derks** [comment]
This is now fixed, thanks!
