### ISSUE TITLE
Tips on deploying a CLI inside the container

### ISSUE THREAD

**Issue by francescobianca** [datafolklabs/cement#622]
Hi, 
I have developed my CLI and locally everything is ok. Now I would like to deploy it via docker container. However, I can't get the .rc file for auto-complete to work (I don't want to source file.rc every time inside the container). Do you have experience with this?

**System Information**

- Cement Version: Cement Framework 3.0.6
- Python Version: Python 3.9.10
- Operating System and Version: Platform Linux-5.13.0-1028-oem-x86_64-with

**Example**

Docker file:

```yaml
FROM python:3.9-alpine
LABEL MAINTAINER=
ENV PS1=

WORKDIR /src
COPY . /src

RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]

RUN pip install --no-cache-dir -r requirements.txt \
    && python setup.py install \
    && source file.rc

WORKDIR /

ENTRYPOINT ["/bin/bash"]
```

I started the container like this:

```bash
$ docker run -it --rm my_image
```

But autocomplete is not active. I have to manually launch:
```bash
$ source src/file.rc
```

This mechanism is not the best in the usability of the application. Suggestions?

Thanks in advance

[MCVE]: https://stackoverflow.com/help/mcve

**Comment by derks** [comment]
@francescobianca would you mind sharing your autocomplete config (or an example of it)? Wouldn't mind adding this to the docs.

**Comment by francescobianca** [comment]
Hi @derks no problem,

I defined an .rc file in the root of the project. Something similar to [this](https://cement.readthedocs.io/en/stable-2.4.x/examples/bash_auto_completion/#example-bash-rc).

To have it automatically launch inside the container:

```yaml
FROM python:3.9-alpine
LABEL MAINTAINER="..."
ENV PS1="\[\e[0;33m\]|> ... <| \[\e[1;35m\]\W\[\e[0m\] \[\e[0m\]# "

WORKDIR /src
COPY . /src

RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]

RUN pip install --no-cache-dir -r requirements.txt \
    && python setup.py install \
    && echo "source /src/file.rc" >> ~/.bashrc

WORKDIR /

CMD ["/bin/bash"]

LABEL ...
```

And the container run:
```bash
$ docker run -it --rm my_image
```
