### ISSUE TITLE
Help wanted - Packaging and distribution

### ISSUE THREAD

**Issue by PraneethKarnena** [datafolklabs/cement#648]
# Help wanted - Packaging and distribution

Need help with packaging and distributing a CLI application built using Cement.

The documentation section on the same is incomplete. Please provide detailed info on packaging and distributing CLI apps.

**System Information**

- Cement Version: stable/3.0
- Python Version: 3.8
- Operating System and Version: Windows 10

**Comment by derks** [comment]
@PraneethKarnena can you please clarify "packaging"? This often depends on the destination OS, for example RPM/DPKG/APK for Linux just as an example... for Windows you may wish to distribute through [Chocolatey](https://chocolatey.org/). The easiest approach, and a Python standard, is to distribute via PyPi (ex: `pip install myapp`). This would be my first approach, as this is cross platform ... and then would look further into distribution with native operating system mechanisms if that were preferred.

For PyPi distribution, the project template for Cement (ex: `cement generate project`) includes stubs for doing this with `twine`, and there are helpers in the `Makefile`:

```
dist: clean
	rm -rf dist/*
	python setup.py sdist
	python setup.py bdist_wheel

dist-upload:
	twine upload dist/*
```


The following is included in the generated `README`:

**Releasing to PyPi**

Before releasing to PyPi, you must configure your login credentials:

*~/.pypirc*:

```
[pypi]
username = __token__
password = YOUR_PYPI_API_TOKEN
Then use the included helper function via the Makefile:
```

Then:

```
$ make dist

$ make dist-upload
```


Ref:

- https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by PraneethKarnena** [comment]
Thanks. It worked.
