### ISSUE TITLE
Release 3.10.x or 3.2.x // Timeline

### ISSUE THREAD

**Issue by TomFreudenberg** [datafolklabs/cement#666]
Dear @derks we are starting a new project and I wonder which version we should use?

Since 3.0.8 was already released a long time ago, it seems that tag 3.0.9 would also be stable?

I would prefer to use even the main branch due to the support for Python 3.12 and the change from fatal to critical log.

I'm not sure how "unstable" you consider the main branch to be.

Do you already have an idea for a next release?

Thanks for your feedback in advance
Tom

Translated with DeepL.com (free version)

**Comment by derks** [comment]
Main is very stable in line with release. Use main until 3.0.10 is out. 3.2 is not planned officially or started.

**Comment by TomFreudenberg** [comment]
Thanks a lot for that fast reply.

Cheers
Tom
