### ISSUE TITLE
ext_smtp.py sends empty (wrong) email addresses in server dialog

### ISSUE THREAD

**Issue by TomFreudenberg** [datafolklabs/cement#668]
The current code will send empty addresses as RCPT TO: dialog `<>` which cause errors e.g. on mailersend service.

https://github.com/datafolklabs/cement/blob/ea320570d7951483955637cfd8370bd7744f723e/cement/ext/ext_smtp.py#L135-L136

Code should be:

```python
        if params['cc']:
            msg['Cc'] = ', '.join(params['cc'])
        if params['bcc']:
            msg['Bcc'] = ', '.join(params['bcc'])
```

If you like I can make a PR for both tickets

Cheers
Tom

**Comment by derks** [comment]
Resolved in `main`, will be released with `stable/3.0.10`.
