### ISSUE TITLE
Implement Ruff for Code Compliance

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#671]
Flake8 has been great, and have had no issue with it. Ruff is the new cool kid... worth a look, primarily as it potentially solves other issues and/or provides additional features all in one utility:

- https://pypi.org/project/ruff/

Related:

- https://github.com/datafolklabs/cement/pull/664

**Comment by sigma67** [comment]
I can tackle this as I have some experience with ruff. 

I would start with a minimal config that requires almost no changes to the code and introduce rules one-by-one thereafter.

**Comment by derks** [comment]
Implemented via PR #681 .... thank you @sigma67 !
