### ISSUE TITLE
Failure on 2.10.x branch using Python 3.12

### ISSUE THREAD

**Issue by rahulrajaram** [datafolklabs/cement#672]
# Cement Issue Reporting and Feature Requests

Please include any of the following in bug/issue reports where it is relevant:

**System Information**

- Cement Version: 2.10.x
- Python Version: 3.12
- Operating System and Version: All

**Steps to Reproduce (Bugs Only)**

- set environment Python version to 3.12
- Create new Python Package
- Add dependency on Cement 2.10.x
- Build Cement app

Observed:

- App will crash when attempting to load plugins because of lingering dependencies on `imp` in cement/ext/ext_plugin

Desired:

- App loads without any problems

** Further context **

I am from the AWS Elastic Beanstalk (EB) team which owns the EB CLI. The EB CLI has a dependency on `cement` 2.x. We are unable to upgrade to 3.x at this time, and have identified that a change to the 2.10.x would fix our issues. I will follow up with a PR to fix the issue on the stable/2.10.x branch to remove lingering references to cement and would appreciate if you accept it.

**Comment by derks** [comment]
@rahulrajaram this fix has been merged, and 2.10.14 has been released. Can you please verify it before I close this issue out?

- https://pypi.org/project/cement/2.10.14/

**Comment by rahulrajaram** [comment]
@derks , thanks! It works.
