### ISSUE TITLE
Modernize Packaging: pyproject.toml

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#680]
Need to modernize packaging around pyproject.toml:

- https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

Care to be had with backward compat.... perhaps this should be slated for 3.2. Additionally, should poetry or the like be considered?

**Comment by sigma67** [comment]
I was about to tackle this right now as a prerequisite for ruff and then I saw you already opened an issue :)

I would recommend using a package manger, definitely.

I would go with `pdm`, as I have more experience with it and it is generally more standards compliant than poetry
