### ISSUE TITLE
Python 3.12 / Elastic Beanstalk CLI require importlib, not 'imp'

### ISSUE THREAD

**Issue by kodexArg** [datafolklabs/cement#737]
## System Information
Cement Version: 2.8.2
Python Version: 3.12
Operating System: Ubuntu 24.04

## Description
The current version of Cement (2.8.2) uses the imp module, which has been removed in Python 3.12. This causes compatibility issues when using Cement with Python 3.12, particularly when installing and running awsebcli.

## Suggested Fix
The import imp lines should be replaced with import importlib in the following files:
- cement/ext/ext_plugin.py (line 27)
- cement/core/foundation.py (line 18), inside the if sys.version_info... block
- cement/core/extension.py (line 8), also inside the if sys.version_info... block

After making these changes locally, awsebcli functions correctly with Python 3.12.

**Comment by derks** [comment]
@kodexArg this issue was fixed a few months ago in Cement 2.10.x .... which is the latest and FINAL branch of Cement 2.x.

You will need to update to latest version of EBS I believe.

- https://github.com/datafolklabs/cement/issues/672
