### ISSUE TITLE
Documentation Request: VSCode Debugging

### ISSUE THREAD

**Issue by NateLedet** [datafolklabs/cement#738]
# VSCode Debugging setup

## **Request**
Documentation Addition: 
Set up debugging in VSCode for a Cement based CLI tool. 

### System Information

- Cement Version: 3.x
- Python Version: 3.x
- Operating System and Version: Windows 11 (not yet tested on Linux/MacOS)

### **Steps to Implement**
- Create or Modify **launch.json** 
  - Run > Open Configurations
  - Run > Add Configurations
    - Select Python Debugger > Module > *project_name.main* (ie: todo.main)

Modify the configuration code block to allow for arguments/options:

`launch.json`
```json
"configurations": [
  {
    "name": "Python Debugger: Cement CLI Tool",
    "type": "debugpy",
    "request": "launch",
    "module": "todo.main"
    "console": "integratedTerminal",
    "args": "${command:pickArgs}"
  }
]
```
The above configuration will prompt for arguments/options when Debug runs. An alternative to is to hard-code the args/options if you're frequently debugging a specific piece of your code:

```json
    "args": [ "list", "-h" ]
```

**Comment by derks** [comment]
Thank you @NateLedet, a draft has been added to the docs... I have not tested myself, however it looks straight forward enough. I appreciate you contribution, and hope it helps others that might be looking for it.

- https://docs.builtoncement.com/additional-topics/debugging-with-vscode
